using System.Text;

namespace XamlCheck;

/// <summary>Writes Xaml.Stubs.g.cs: for every x:Class the partial the XAML compiler would generate, reduced to the x:Name fields and InitializeComponent().</summary>
static class StubWriter
{
    public static void Write(string path, IEnumerable<XamlClass> classes, string repoRoot)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Written by tools/xamlcheck on every run. Stands in for the XAML compiler's *.g.i.cs off");
        sb.AppendLine("// Windows: the x:Name fields and the InitializeComponent() each code-behind calls, nothing else.");
        sb.AppendLine("#pragma warning disable CS8618, CS0169, CS0649, CS0414, CS0067");
        foreach (var group in classes.DistinctBy(c => c.FullName).GroupBy(c => c.Namespace).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var indent = "";
            if (group.Key.Length > 0)
            {
                sb.AppendLine().AppendLine($"namespace {group.Key}").AppendLine("{");
                indent = "    ";
            }
            foreach (var c in group.OrderBy(c => c.Name, StringComparer.Ordinal))
            {
                sb.AppendLine($"{indent}// {Path.GetRelativePath(repoRoot, c.File)}");
                sb.Append($"{indent}partial class {c.Name}");
                if (c.BaseTypeFullName is not null) sb.Append($" : global::{c.BaseTypeFullName}");
                sb.AppendLine().AppendLine($"{indent}{{");
                foreach (var f in c.Fields)
                    sb.AppendLine($"{indent}    {f.Modifier} global::{f.TypeFullName} {f.Name};");
                sb.AppendLine($"{indent}    private void InitializeComponent() {{ }}");
                if (c.WantsConnect)
                    sb.AppendLine($"{indent}    protected virtual void Connect(int connectionId, object target) {{ }}");
                sb.AppendLine($"{indent}}}");
            }
            if (group.Key.Length > 0) sb.AppendLine("}");
        }
        File.WriteAllText(path, sb.ToString());
    }
}
