using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Md.Core.Markdown;

namespace Md.Core.Tests;

// The ```plot fence, against the oracle the site itself produced.
//
// Fixtures/plot-vectors.json was generated by running nettrash.me's own Rust
// (render_plot_svg, nice_step, format_label, preprocess_math_expr) over 403
// inputs: 81 tick spacings, 100 tick labels (each with the four Rust primitives
// that produced it), 162 evaluations, 38 malformed expressions and 22 whole
// figures. Every number is recorded twice, as JSON and as the IEEE-754 bit
// pattern, so "close enough" cannot creep in.
//
// It is an oracle, not a specification. Six of the behaviours it records are
// bugs, and this suite asserts the FIXED behaviour for those, in tables that
// name each one and what the site did. Everything else must match the vector
// exactly — there is no third category, and no row is skipped.
//
// This is the port of md.macOS/mdTests/PlotTests.swift, case for case (§8, the
// renderer/export integration, belongs to the modules it exercises and is not
// here), plus the two guards the Swift suite says it cannot express and the
// Kotlin/TypeScript suites carry: the decade mechanism (a wrong log10 must not
// move a step) and the well-formed-XML check. §9 pins the same 31,647 bytes the
// other four ports pin.
//
// Every string assertion here is ordinal. xUnit's Assert.Contains(string,
// string) is culture-sensitive by default, so it is never used on strings.
public class PlotTests
{
    // MARK: - The corpus

    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    private sealed record NiceStepRow(double Input, string InputLabel, string InputBits, string OutputBits);

    private sealed record FormatLabelRow(double Input, string InputLabel, string InputBits, string Output,
        string Fmt1e, string Fmt2f);

    /// <summary>
    /// <c>Result</c>/<c>ResultBits</c> are null for the rows the site could not
    /// evaluate at all (the JSON string <c>"none"</c>) — every one a corrected
    /// behaviour or a name this language does not have, and the loop fails if
    /// any is neither.
    /// </summary>
    private sealed record EvalRow(string Expr, double X, string XLabel, string XBits, double? Result, string? ResultBits);

    private sealed record SvgRow(string Name, string Expr, double XMin, double XMax, double YMin, double YMax,
        string? FirstPoint, string? LastPoint, int PolylineCount, int LineCount, int TextCount,
        double XStep, double YStep, string[] XTickLabels, string[] YTickLabels);

    private sealed record Vectors(NiceStepRow[] NiceStep, FormatLabelRow[] FormatLabel, EvalRow[] Eval,
        string[] ParseErrors, SvgRow[] Svg);

    private static string Fixture(params string[] parts)
    {
        var path = AppContext.BaseDirectory;
        path = Path.Combine(path, "Fixtures");
        foreach (var part in parts) path = Path.Combine(path, part);
        return path;
    }

    /// <summary>
    /// Read once. System.Text.Json parses doubles correctly rounded (the
    /// per-row *Bits assertions below prove it on every input); the non-finite
    /// values are the JSON strings <c>nan</c>, <c>inf</c>, <c>-inf</c>.
    /// </summary>
    private static readonly Lazy<Vectors> Corpus = new(() =>
    {
        using var document = JsonDocument.Parse(File.ReadAllBytes(Fixture("plot-vectors.json")));
        var root = document.RootElement;

        var niceStep = new List<NiceStepRow>();
        foreach (var row in root.GetProperty("niceStep").EnumerateArray())
        {
            niceStep.Add(new NiceStepRow(Real(row.GetProperty("input")), Label(row.GetProperty("input")),
                row.GetProperty("inputBits").GetString()!, row.GetProperty("outputBits").GetString()!));
        }

        var formatLabel = new List<FormatLabelRow>();
        foreach (var row in root.GetProperty("formatLabel").EnumerateArray())
        {
            var primitives = row.GetProperty("rustPrimitives");
            formatLabel.Add(new FormatLabelRow(Real(row.GetProperty("input")), Label(row.GetProperty("input")),
                row.GetProperty("inputBits").GetString()!, row.GetProperty("output").GetString()!,
                primitives.GetProperty("fmt_1e").GetString()!, primitives.GetProperty("fmt_2f").GetString()!));
        }

        var eval = new List<EvalRow>();
        foreach (var row in root.GetProperty("eval").EnumerateArray())
        {
            var result = row.GetProperty("result");
            var bits = row.GetProperty("resultBits");
            var none = result.ValueKind == JsonValueKind.Null
                || (result.ValueKind == JsonValueKind.String && result.GetString() == "none")
                || bits.ValueKind == JsonValueKind.Null;
            eval.Add(new EvalRow(row.GetProperty("expr").GetString()!, Real(row.GetProperty("x")),
                Label(row.GetProperty("x")), row.GetProperty("xBits").GetString()!,
                none ? null : Real(result), none ? null : bits.GetString()));
        }

        var parseErrors = new List<string>();
        foreach (var row in root.GetProperty("parseErrors").EnumerateArray())
        {
            parseErrors.Add(row.GetProperty("expr").GetString()!);
        }

        var svg = new List<SvgRow>();
        foreach (var row in root.GetProperty("svg").EnumerateArray())
        {
            svg.Add(new SvgRow(row.GetProperty("name").GetString()!, row.GetProperty("expr").GetString()!,
                row.GetProperty("xMin").GetDouble(), row.GetProperty("xMax").GetDouble(),
                row.GetProperty("yMin").GetDouble(), row.GetProperty("yMax").GetDouble(),
                OptionalString(row.GetProperty("firstPoint")), OptionalString(row.GetProperty("lastPoint")),
                row.GetProperty("polylineCount").GetInt32(), row.GetProperty("lineCount").GetInt32(),
                row.GetProperty("textCount").GetInt32(),
                row.GetProperty("xStep").GetDouble(), row.GetProperty("yStep").GetDouble(),
                Strings(row.GetProperty("xTickLabels")), Strings(row.GetProperty("yTickLabels"))));
        }

        return new Vectors(niceStep.ToArray(), formatLabel.ToArray(), eval.ToArray(), parseErrors.ToArray(),
            svg.ToArray());
    });

    private static Vectors V => Corpus.Value;

    private static double Real(JsonElement element)
    {
        if (element.ValueKind == JsonValueKind.Number) return element.GetDouble();
        var text = element.GetString()!;
        if (text == "nan") return double.NaN;
        if (text == "inf") return double.PositiveInfinity;
        if (text == "-inf") return double.NegativeInfinity;
        return double.TryParse(text, NumberStyles.Float, Inv, out var value) ? value : double.NaN;
    }

    private static string Label(JsonElement element) =>
        element.ValueKind == JsonValueKind.Number ? element.GetDouble().ToString("R", Inv) : element.GetString()!;

    private static string? OptionalString(JsonElement element) =>
        element.ValueKind == JsonValueKind.Null ? null : element.GetString();

    private static string[] Strings(JsonElement array)
    {
        var out_ = new List<string>();
        foreach (var item in array.EnumerateArray()) out_.Add(item.GetString()!);
        return out_.ToArray();
    }

    /// <summary>The big-endian IEEE-754 bit pattern, the way the vectors record a double.</summary>
    private static string Bits(double value) => BitConverter.DoubleToInt64Bits(value).ToString("x16", Inv);

    /// <summary>
    /// Bit equality, with NaN compared as NaN and never by payload or sign:
    /// .NET's <c>double.NaN</c> is <c>fff8000000000000</c> and this runtime's
    /// <c>log10</c> of a negative number returns the same, where Rust's oracle
    /// recorded <c>7ff8000000000000</c>. No program can tell them apart.
    /// </summary>
    private static void AssertBits(string want, double got, string label)
    {
        if (double.IsNaN(got))
        {
            Assert.True(IsNaNBits(want), label + " = NaN, want " + want);
            return;
        }
        Assert.True(want == Bits(got), label + " = " + Bits(got) + ", want " + want);
    }

    private static bool IsNaNBits(string bits) =>
        double.IsNaN(BitConverter.Int64BitsToDouble(unchecked((long)ulong.Parse(bits, NumberStyles.HexNumber, Inv))));

    /// <summary>
    /// The functions of the plot language that IEEE-754 lists as RECOMMENDED rather than
    /// required (clause 9.2), plus <c>^</c>. Every implementation is free to be up to an ulp
    /// off on these, and the platforms really do disagree: the oracle in
    /// <c>plot-vectors.json</c> was recorded by the site's Rust on Darwin, and CI found
    /// <c>atanh(0.5)</c> one ulp low on Linux/glibc (3fe193ea7aad030a vs ...030b) and
    /// <c>asin(0.5)</c> one ulp high on Windows/UCRT (3fe0c152382d7366 vs ...7365).
    ///
    /// So a row that reaches one of these is held to "within one ulp of the oracle" and every
    /// other row stays bit-exact. That is not a softened assertion but the right one: the four
    /// operations IEEE-754 DOES require to be correctly rounded (+ - * /), <c>sqrt</c>, the
    /// comparisons, the roundings and the decimal conversions are all still pinned to the bit,
    /// which is what catches a wrong formula, a wrong precedence or a wrong constant. What the
    /// figure promises — that every port draws the same bytes — is pinned separately and
    /// exactly by the golden-figure tests, because a coordinate is written to two decimals and
    /// an ulp cannot move one.
    /// </summary>
    private static readonly string[] RecommendedOperations =
    [
        "sin", "cos", "tan", "asin", "acos", "atan", "atan2",
        "sinh", "cosh", "tanh", "asinh", "acosh", "atanh",
        "exp", "exp2", "ln", "log", "log2", "log10", "pow", "hypot", "cbrt",
    ];

    /// <summary>Does this expression reach a function whose last bit the platform owns?</summary>
    private static bool UsesRecommendedOperation(string expr)
    {
        if (expr.Contains('^', StringComparison.Ordinal)) return true;   // pow, by another spelling
        foreach (Match m in Regex.Matches(expr, "[A-Za-z_][A-Za-z0-9_]*", RegexOptions.CultureInvariant))
            if (Array.IndexOf(RecommendedOperations, m.Value) >= 0) return true;
        return false;
    }

    /// <summary>
    /// Distance in representable doubles. <c>long.MaxValue</c> when the two are not even on the
    /// same side of zero, so a sign flip (or +0 against -0, which the corpus records apart) can
    /// never pass as "close enough".
    /// </summary>
    private static long UlpDistance(double a, double b)
    {
        var ia = BitConverter.DoubleToInt64Bits(a);
        var ib = BitConverter.DoubleToInt64Bits(b);
        if ((ia < 0) != (ib < 0)) return ia == ib ? 0 : long.MaxValue;
        return Math.Abs(ia - ib);
    }

    private static double Value(string expr, double x) => Plot.Evaluate(Plot.ParseExpression(expr, "x"), "x", x);

    private static double Literal(string text) => double.Parse(text, NumberStyles.Float, Inv);

    private static string Lines(params string[] lines) => string.Join("\n", lines);

    private static string Repeat(string s, int count)
    {
        var out_ = new StringBuilder(s.Length * count);
        for (var i = 0; i < count; i++) out_.Append(s);
        return out_.ToString();
    }

    // Ordinal string assertions. Assert.Contains(string, string) compares by
    // the current culture, which is exactly the class of bug this port exists
    // to keep out.
    private static void Has(string haystack, string needle, string? note = null) =>
        Assert.True(haystack.Contains(needle, StringComparison.Ordinal),
            (note ?? "") + " expected to contain '" + needle + "' in: " + Clip(haystack));

    private static void Lacks(string haystack, string needle, string? note = null) =>
        Assert.False(haystack.Contains(needle, StringComparison.Ordinal),
            (note ?? "") + " expected NOT to contain '" + needle + "' in: " + Clip(haystack));

    private static void StartsWith(string text, string prefix) =>
        Assert.True(text.StartsWith(prefix, StringComparison.Ordinal), "expected prefix '" + prefix + "' in: " + Clip(text));

    private static void EndsWith(string text, string suffix) =>
        Assert.True(text.EndsWith(suffix, StringComparison.Ordinal), "expected suffix '" + suffix + "' in: " + Clip(text));

    private static string Clip(string s) => s.Length <= 200 ? s : s.Substring(0, 200) + "…";

    /// <summary>Assert that <paramref name="body"/> throws a <see cref="PlotException"/> whose message contains <paramref name="message"/>.</summary>
    private static PlotException AssertPlotError(Action body, string message, string note = "")
    {
        PlotException? caught = null;
        try
        {
            body();
        }
        catch (PlotException error)
        {
            caught = error;
        }
        Assert.True(caught is not null, "expected a PlotException containing '" + message + "' " + note);
        if (message.Length != 0)
        {
            Assert.True(caught!.Message.Contains(message, StringComparison.Ordinal),
                "'" + caught.Message + "' should contain '" + message + "' " + note);
        }
        return caught!;
    }

    private static PlotException AssertPlotError(Func<object?> body, string message, string note = "") =>
        AssertPlotError(() => { _ = body(); }, message, note);

    // MARK: - §1 nice_step — ported verbatim, so every row must match

    [Fact]
    public void NiceStepReproducesAllRecordedSpacings()
    {
        Assert.Equal(81, V.NiceStep.Length);
        foreach (var row in V.NiceStep)
        {
            AssertBits(row.InputBits, row.Input, "the corpus decodes exactly: " + row.InputLabel);
            AssertBits(row.OutputBits, Plot.NiceStep(row.Input), "niceStep(" + row.InputLabel + ")");
        }
    }

    [Fact]
    public void NiceStepTakesEachOfTheFourBranches()
    {
        // norm <= 1.5, <= 3, <= 7, else — the `10 * mag` branch is the one a
        // careless port drops, and it is what draws [-32, 32] with a step of 10.
        Assert.Equal(1, Plot.NiceStep(8));
        Assert.Equal(2, Plot.NiceStep(20));
        Assert.Equal(5, Plot.NiceStep(50));
        Assert.Equal(10, Plot.NiceStep(64));
    }

    // MARK: - §1a The decade is a decimal literal, never pow

    /// <summary>
    /// The contract: the decade is the literal <c>1e&lt;n&gt;</c>, bit for bit,
    /// for all 632 exponents. Darwin's and this runtime's <c>pow</c> happen to be
    /// correct for all 632 too, so this alone would not catch a reintroduced
    /// <c>Math.Pow(10, e)</c> — <see cref="NiceStepSurvivesALog10ThatIsOffByADecade"/>
    /// is the guard that bites on every engine.
    /// </summary>
    [Fact]
    public void DecadeIsTheDecimalLiteralAndNotPow()
    {
        Assert.Equal(Bits(1e-4), Bits(Plot.Decade(-4)));
        Assert.Equal("3f1a36e2eb1c432d", Bits(Plot.Decade(-4)));
        for (var exponent = -323; exponent <= 308; exponent++)
        {
            var expected = Literal("1e" + exponent.ToString(Inv));
            Assert.True(Bits(expected) == Bits(Plot.Decade(exponent)), "decade(" + exponent + ") is the literal 1e" + exponent);
        }
    }

    /// <summary>
    /// The log10 half of the same hazard, on the input that caught it: rough is
    /// strictly below 1e-4, yet <c>floor(log10(rough))</c> is −4 here too.
    /// </summary>
    [Fact]
    public void NiceStepPinsTheExponentAgainstAnUntrustworthyLog10()
    {
        var rough = BitConverter.Int64BitsToDouble(0x3f1a36e2eb1c432c);   // 9.999999999999999e-05
        var range = rough * 8;
        Assert.Equal(-4, Math.Floor(Math.Log10(rough)));
        Assert.True(Plot.Decade(-4) > rough, "yet 1e-4 is strictly above rough");
        Assert.Equal("3f1a36e2eb1c432d", Bits(Plot.NiceStep(range)));
    }

    /// <summary>
    /// The family's mechanism guard, in the shape C# can express: hand
    /// <c>niceStep</c> a log10 that is wrong by a whole decade either way and
    /// demand every oracle row unchanged. A decade built from <c>pow</c> would
    /// pass the literal test on this machine; a pin that trusts <c>log10</c>
    /// cannot pass this one.
    /// </summary>
    [Fact]
    public void NiceStepSurvivesALog10ThatIsOffByADecade()
    {
        var range = 0.0009 - 0.0001;
        Assert.Equal("3f1a36e2eb1c432c", Bits(range / 8));
        Assert.Equal(Bits(1e-4), Bits(Plot.NiceStep(range)));
        var wrongs = new (string Name, Func<double, double> Log10)[]
        {
            ("one decade low", x => Math.Log10(x) - 1),
            ("one decade high", x => Math.Log10(x) + 1),
        };
        foreach (var (name, log10) in wrongs)
        {
            Assert.True(Bits(1e-4) == Bits(Plot.NiceStep(range, log10)), "tiny_range, " + name);
            foreach (var row in V.NiceStep)
            {
                AssertBits(row.OutputBits, Plot.NiceStep(row.Input, log10), "niceStep(" + row.InputLabel + "), " + name);
            }
        }
    }

    /// <summary>The bracket the pin guarantees: <c>mag &lt;= rough &lt; 10 * mag</c>, over the corpus and a decade sweep.</summary>
    [Fact]
    public void EveryDecadeBracketsItsValue()
    {
        var inputs = new List<double>();
        foreach (var row in V.NiceStep) inputs.Add(row.Input);
        for (var exponent = -300; exponent <= 300; exponent++)
        {
            var decade = Literal("1e" + exponent.ToString(Inv));
            inputs.Add(decade * 8);
            inputs.Add(Math.BitDecrement(decade) * 8);
            inputs.Add(Math.BitIncrement(decade) * 8);
        }
        foreach (var range in inputs)
        {
            if (!double.IsFinite(range) || !(range > 0)) continue;
            var rough = range / 8;
            if (!(rough > 0) || !double.IsFinite(rough)) continue;
            var exponent = Math.Floor(Math.Log10(rough));
            if (Plot.Decade(exponent) > rough) exponent -= 1;
            else if (Plot.Decade(exponent + 1) <= rough) exponent += 1;
            var magnitude = Plot.Decade(exponent);
            if (!(magnitude > 0) || !double.IsFinite(magnitude)) continue;
            Assert.True(magnitude <= rough, "mag <= rough for range " + range.ToString("R", Inv));
            Assert.True(rough < Plot.Decade(exponent + 1), "rough < 10*mag for range " + range.ToString("R", Inv));
        }
    }

    /// <summary>The degenerate inputs the corpus records, which <c>pow</c> answered by accident and <c>decade</c> answers on purpose.</summary>
    [Fact]
    public void DecadeReproducesPowsNonFiniteAnswers()
    {
        Assert.True(double.IsNaN(Plot.Decade(double.NaN)), "pow(10, nan) is nan");
        Assert.Equal(double.PositiveInfinity, Plot.Decade(double.PositiveInfinity));
        Assert.Equal(0, Plot.Decade(double.NegativeInfinity));
        Assert.True(double.IsNaN(Plot.NiceStep(double.NaN)));
        Assert.True(double.IsNaN(Plot.NiceStep(-1)));
        Assert.Equal(double.PositiveInfinity, Plot.NiceStep(double.PositiveInfinity));
        Assert.Equal("0000000000000000", Bits(Plot.NiceStep(0)));
        Assert.Equal("0000000000000000", Bits(Plot.NiceStep(5e-324)));
    }

    // The Kotlin suite's three pins on the decade of a value (`decadeOf`), which
    // the mechanism is exposed for.

    [Fact]
    public void TheDecadeOfABoundaryInputIsTheDecimalLiteralNotAPow()
    {
        var rough = BitConverter.Int64BitsToDouble(0x3f1a36e2eb1c432c);
        Assert.Equal(9.999999999999999e-05, rough);
        Assert.True(rough < 1e-4, "one ULP under 1e-4");
        Assert.Equal(-4.0, Math.Floor(Math.Log10(rough)));
        Assert.Equal(Bits(Literal("1e-5")), Bits(Plot.DecadeOf(rough)));
        Assert.Equal(Bits(1e-5), Bits(Plot.DecadeOf(rough)));
        Assert.False(Plot.DecadeOf(rough) == 1e-4, "decade must not be 1e-4");
    }

    /// <summary>A power of ten is its own decade; the double just below it belongs to the decade beneath. Expectations are parsed literals, never computed.</summary>
    [Fact]
    public void EveryDecadeBoundaryResolvesToTheLiteralOnBothSides()
    {
        for (var exponent = -300; exponent <= 300; exponent++)
        {
            var literal = Literal("1e" + exponent.ToString(Inv));
            Assert.True(Bits(literal) == Bits(Plot.DecadeOf(literal)), "decadeOf(1e" + exponent + ")");
            Assert.True(Bits(Literal("1e" + (exponent - 1).ToString(Inv))) == Bits(Plot.DecadeOf(Math.BitDecrement(literal))),
                "decadeOf(nextDown(1e" + exponent + "))");
        }
    }

    [Fact]
    public void TheDecadePinLeavesDegenerateInputsAlone()
    {
        Assert.Equal(Bits(0.0), Bits(Plot.DecadeOf(0.0)));
        Assert.True(double.IsNaN(Plot.DecadeOf(-1.0)));
        Assert.True(double.IsNaN(Plot.DecadeOf(double.NaN)));
        Assert.Equal(Bits(double.PositiveInfinity), Bits(Plot.DecadeOf(double.PositiveInfinity)));
        Assert.True(double.IsNaN(Plot.DecadeOf(double.NegativeInfinity)));
    }

    // MARK: - §2 format_label — ported with two corrections

    /// <summary>
    /// The nine labels the site prints wrong: its integer branch prints
    /// <c>val as i64</c>, which truncates, so a tick one ULP below a whole number
    /// loses a whole unit. The renderer rounds.
    /// </summary>
    private static readonly (double Input, string Site, string Ours)[] CorrectedLabels =
    {
        (0.9999999999, "0", "1"),
        (-0.9999999999, "0", "-1"),
        (2.9999999996, "2", "3"),
        (-2.9999999996, "-2", "-3"),
        (999.9999999999, "999", "1000"),
        (-999.9999999999, "-999", "-1000"),
        (123.99999999995, "123", "124"),
        (-123.99999999995, "-123", "-124"),
        (999.9999999999999, "999", "1000"),
    };

    private static (double Input, string Site, string Ours)? CorrectedLabel(double input)
    {
        if (double.IsNaN(input)) return null;
        foreach (var row in CorrectedLabels) if (row.Input == input) return row;
        return null;
    }

    [Fact]
    public void FormatLabelReproducesEveryRecordedLabelButTheNineTheSiteTruncates()
    {
        Assert.Equal(100, V.FormatLabel.Length);
        var corrected = 0;
        foreach (var row in V.FormatLabel)
        {
            AssertBits(row.InputBits, row.Input, "the corpus decodes exactly: " + row.InputLabel);
            var got = Plot.FormatLabel(row.Input);
            var fix = CorrectedLabel(row.Input);
            if (fix is not null)
            {
                Assert.True(fix.Value.Site == row.Output, "the vector still records the site's " + row.InputLabel);
                Assert.True(fix.Value.Ours == got, "formatLabel(" + row.InputLabel + ") = " + got);
                corrected += 1;
            }
            else
            {
                Assert.True(row.Output == got, "formatLabel(" + row.InputLabel + ") = " + got + ", want " + row.Output);
            }
        }
        // Every row of the correction table was reached — a table entry that no
        // vector exercises is a claim about nothing.
        Assert.Equal(CorrectedLabels.Length, corrected);
    }

    [Fact]
    public void FormatLabelWritesRustsExponentialNotThePlatforms()
    {
        // THE cross-platform hazard, pinned on all 100 values: `1.0e3` and not
        // `1.0e+3` (JavaScript), `1.0e+03` (C, Java) or `1.2E+003` (.NET's "E1");
        // and ties to even on the exact binary value.
        foreach (var row in V.FormatLabel)
        {
            Assert.True(row.Fmt1e == Plot.FormatExponential(row.Input, 1),
                "{:.1e} of " + row.InputLabel + " = " + Plot.FormatExponential(row.Input, 1) + ", want " + row.Fmt1e);
        }
        // What the platform would have said — the spelling the formatter exists
        // to avoid.
        Assert.Equal("1.2E+003", 1250.0.ToString("E1", Inv));
        Assert.Equal("1.2e3", Plot.FormatExponential(1250, 1));     // 1.25 → ties to even
        Assert.Equal("1.4e3", Plot.FormatExponential(1350, 1));     // 1.35 → ties to even, upward
        Assert.Equal("1.3e-2", Plot.FormatExponential(0.0125, 1));  // not a tie: the double is above it
        Assert.Equal("4.9e-324", Plot.FormatExponential(5e-324, 1)); // the smallest subnormal
        Assert.Equal("1.0e3", Plot.FormatExponential(1000, 1));
        Assert.Equal("5.0e-3", Plot.FormatExponential(0.005, 1));
        Assert.Equal("1.0e300", Plot.FormatExponential(1e300, 1));
        Assert.Equal("-0.0e0", Plot.FormatExponential(-0.0, 1));
        Assert.Equal("0.0e0", Plot.FormatExponential(0, 1));
        Assert.Equal("inf", Plot.FormatExponential(double.PositiveInfinity, 1));
        Assert.Equal("-inf", Plot.FormatExponential(double.NegativeInfinity, 1));
        Assert.Equal("NaN", Plot.FormatExponential(double.NaN, 1));
    }

    [Fact]
    public void FormatLabelWritesRustsFixedFormNotThePlatforms()
    {
        foreach (var row in V.FormatLabel)
        {
            // Past 25 significant digits `{:.2}` prints the double's whole exact
            // expansion (1e300 is 301 digits of it). format_label sends everything
            // from 1000 up to the exponential branch, so the fixed formatter is
            // never asked for one, and it stops at the digits it can decide a
            // rounding on.
            if (row.Fmt2f.Length > 30) continue;
            Assert.True(row.Fmt2f == Plot.FormatFixed(row.Input, 2),
                "{:.2} of " + row.InputLabel + " = " + Plot.FormatFixed(row.Input, 2) + ", want " + row.Fmt2f);
        }
        Assert.Equal("0.12", Plot.FormatFixed(0.125, 2));     // an exact tie, rounded to even
        Assert.Equal("8.12", Plot.FormatFixed(8.125, 2));
        Assert.Equal("2.67", Plot.FormatFixed(2.675, 2));     // the double is below the tie
        Assert.Equal("1000.00", Plot.FormatFixed(999.999, 2)); // the carry runs off the fraction
        Assert.Equal("-0.00", Plot.FormatFixed(-0.0, 2));     // Rust keeps the sign
        Assert.Equal("2.50", Plot.FormatFixed(2.5, 2));
        Assert.Equal("1000.00", Plot.FormatFixed(1000, 2));
        Assert.Equal("40.0", Plot.FormatFixed(40, 1));
        Assert.Equal("307.2", Plot.FormatFixed(307.25, 1));   // the golden's grid line: 307.25 is exact, ties to even
        Assert.Equal("237.8", Plot.FormatFixed(237.75, 1));
        Assert.Equal("14.0", Plot.FormatFixed(14, 1));
        Assert.Equal("3", Plot.FormatFixed(3, 0));
        Assert.Equal("inf", Plot.FormatFixed(double.PositiveInfinity, 2));
        Assert.Equal("NaN", Plot.FormatFixed(double.NaN, 2));
    }

    // MARK: - §3 The expression language

    /// <summary>The evaluations where this renderer deliberately answers differently.</summary>
    private static readonly (string Expr, double? X, double Value, string Why)[] CorrectedEval =
    {
        // 1. floor / ceil / round draw.
        ("floor(x)", 2.7, 2, "floor works"),
        ("floor(x)", -2.5, -3, "floor works"),
        ("ceil(x)", 2.1, 3, "ceil works"),
        ("ceil(x)", -2.5, -2, "ceil works"),
        ("round(x)", 2.5, 3, "round works, ties away from zero"),
        ("round(x)", -2.5, -3, "round works, ties away from zero"),
        ("round(x)", 0.5, 1, "round works, ties away from zero"),
        // 2. Comparisons and the Boolean operators are numbers, so they compose.
        ("x==1", 1, 1, "comparisons yield 1.0 / 0.0"),
        ("x!=1", 1, 0, "comparisons yield 1.0 / 0.0"),
        ("x<1", 0, 1, "comparisons yield 1.0 / 0.0"),
        ("x<=1", 1, 1, "comparisons yield 1.0 / 0.0"),
        ("x>1", 2, 1, "comparisons yield 1.0 / 0.0"),
        ("x>=1", 1, 1, "comparisons yield 1.0 / 0.0"),
        ("(x>0)*2", 1, 2, "a comparison multiplies"),
        ("!x", 1, 0, "negation is numeric"),
        ("1&&1", null, 1, "a number is a truth value"),
        ("1<2<3", null, 1, "comparisons chain left-associatively"),
        // 3. `^` is right-associative.
        ("2^3^2", null, 512, "2^(3^2), not (2^3)^2"),
        // 4. Everything is a double.
        ("5/2", null, 2.5, "no integer division"),
        ("-7/2", null, -3.5, "no integer division"),
        ("7/2", null, 3.5, "no integer division"),
        ("2+3*4-5/2", null, 11.5, "no integer division"),
        ("1/0", null, double.PositiveInfinity, "division by zero is ±∞, not an error"),
        ("0/0", null, double.NaN, "0/0 is NaN, not an error"),
        ("1%0", null, double.NaN, "x%0 is NaN, not an error"),
    };

    /// <summary>Expressions this language does not have — every one a parse error here.</summary>
    private static readonly string[] NotInTheLanguage =
    {
        // Not in the roster. evalexpr carries them; the four ports share a roster.
        "min(x,0)", "max(x,0)", "if(x>0,1,-1)", "log(8,2)", "typeof(x)",
        // The site's preprocessor showing through.
        "math::floor(x)", "math::sin(x)", "math::math::sin(x)", "math::log(8,2)",
        // Unknown names, and names that are nearly right.
        "mysin(x)", "x_sin(x)", "SIN(x)", "sinx", "foo(x)", "y", "X",
        "true&&false", "true||false", "!true",
        // Wrong arity — an error, not a silently empty chart.
        "sqrt(1,2)", "hypot(3)", "atan2(1)", "sin()",
        // Types and syntax the language has no use for.
        "\"abc\"", "(1,2)", "x=1", "0x10",
    };

    // There is no libm-tolerance table. The Swift suite records that an earlier
    // one (atanh/asin/acos at 0.5, 1e-15 relative) was false — Darwin matched
    // the oracle exactly — and .NET 10 on macOS matches all 162 rows bit for bit
    // too. If a machine ever does disagree, name that machine and that row here
    // with its bits; do not restore a blanket tolerance.

    private static (double Value, string Why)? Corrected(string expr, double x)
    {
        foreach (var row in CorrectedEval)
        {
            if (row.Expr != expr) continue;
            if (row.X is double wanted && wanted != x) continue;
            return (row.Value, row.Why);
        }
        return null;
    }

    [Fact]
    public void ExpressionLanguageAccountsForEveryRecordedEvaluation()
    {
        Assert.Equal(162, V.Eval.Length);
        var seenCorrections = new HashSet<string>(StringComparer.Ordinal);
        var seenAbsences = new HashSet<string>(StringComparer.Ordinal);
        var divergences = new List<string>();

        foreach (var row in V.Eval)
        {
            var x = row.X;
            var label = row.Expr + " at x=" + row.XLabel;
            AssertBits(row.XBits, x, "the corpus decodes exactly: " + label);

            var fix = Corrected(row.Expr, x);
            if (fix is not null)
            {
                seenCorrections.Add(row.Expr);
                var got = Value(row.Expr, x);
                if (double.IsNaN(fix.Value.Value)) Assert.True(double.IsNaN(got), label);
                else Assert.True(fix.Value.Value == got, label + " — " + fix.Value.Why + " (got " + got.ToString("R", Inv) + ")");
                continue;
            }

            if (Array.IndexOf(NotInTheLanguage, row.Expr) >= 0)
            {
                seenAbsences.Add(row.Expr);
                AssertPlotError(() => Value(row.Expr, x), "", label);
                continue;
            }

            Assert.True(row.Result is not null && row.ResultBits is not null,
                label + ": the site recorded no result, and no table claims the row");
            var want = row.Result!.Value;
            var value = Value(row.Expr, x);
            if (double.IsNaN(want))
            {
                // NaN and not its payload: a runtime may return a quiet NaN spelt
                // 7ffc000000000000 where Rust's returns 7ff8000000000000.
                Assert.True(double.IsNaN(value), label);
                continue;
            }
            if (row.ResultBits == Bits(value)) continue;

            // Report every divergent row, not just the first: one CI run on a second libm
            // should tell us the whole story rather than one line of it.
            var slack = UsesRecommendedOperation(row.Expr)
                ? UlpDistance(value, BitConverter.Int64BitsToDouble(
                      unchecked((long)ulong.Parse(row.ResultBits!, NumberStyles.HexNumber, Inv))))
                : long.MaxValue;
            if (slack > 1)
                divergences.Add(label + " = " + Bits(value) + ", want " + row.ResultBits
                    + (slack == long.MaxValue ? "" : " (" + slack.ToString(Inv) + " ulp)"));
        }

        // An ulp of drift in a recommended operation is the platform's, and is recorded rather
        // than asserted away; anything else fails, with every offending row named.
        Assert.True(divergences.Count == 0, string.Join("\n", divergences));

        // Both tables are fully exercised by the corpus.
        var distinct = new HashSet<string>(StringComparer.Ordinal);
        foreach (var row in CorrectedEval) distinct.Add(row.Expr);
        Assert.Equal(distinct.Count, seenCorrections.Count);
        Assert.Equal(NotInTheLanguage.Length, seenAbsences.Count);
    }

    [Fact]
    public void ExpressionLanguageRejectsEveryMalformedExpression()
    {
        Assert.Equal(38, V.ParseErrors.Length);
        foreach (var expr in V.ParseErrors)
        {
            // Two of the site's failures are not failures here, and both are in
            // the grammar on purpose: `floor(x)` is correction 1, and `x ++ 2` is
            // `x + (+2)` — unary plus is a prefix operator.
            if (expr == "floor(x)" || expr == "x ++ 2") continue;
            AssertPlotError(() => Value(expr, 1), "", expr);
        }
        Assert.Equal(2, Value("floor(x)", 2.7));
        Assert.Equal(3, Value("x ++ 2", 1));
    }

    [Fact]
    public void ExpressionLanguageSaysWhatIsWrongInTheWordsTheSpecUses()
    {
        AssertPlotError(() => Value("sinc(x)", 1), "unknown function 'sinc'");
        AssertPlotError(() => Value("sin(x", 1), "expected ')'");
        AssertPlotError(() => Value("sqrt(1,2)", 1), "sqrt takes 1 argument, not 2");
        AssertPlotError(() => Value("y", 1), "unknown name 'y'");
        AssertPlotError(() => Value("atan2(1)", 1), "atan2 takes 2 arguments, not 1");
        AssertPlotError(() => Value("", 1), "the expression ends too early");
        AssertPlotError(() => Value("x)", 1), "unmatched ')'");
        AssertPlotError(() => Value("x ** 2", 1), "unexpected '*'");
        AssertPlotError(() => Value("0x10", 1), "unexpected 'x10'");
        AssertPlotError(() => Value("1.2.3", 1), "unexpected '.3'");
        AssertPlotError(() => Value("2e", 1), "unexpected 'e'");
        AssertPlotError(() => Value("x(2)", 1), "unknown function 'x'");
        AssertPlotError(() => Value("pi(1)", 1), "unknown function 'pi'");
        AssertPlotError(() => Value("x = 1", 1), "unexpected character '='");
        AssertPlotError(() => Value("x;y", 1), "unexpected character ';'");
    }

    [Fact]
    public void ExpressionLanguageBindsUnaryMinusLooserThanPowerAndPowerToTheRight()
    {
        Assert.Equal(512, Value("2^3^2", 0));
        Assert.Equal(512, Value("2^(3^2)", 0));
        Assert.Equal(64, Value("(2^3)^2", 0));
        Assert.Equal(-9, Value("-x^2", 3));
        Assert.Equal(9, Value("(-x)^2", 3));
        Assert.Equal(-4, Value("-2^2", 0));
        Assert.Equal(0.5, Value("2^-1", 0));
        Assert.Equal(-3, Value("-x", 3));
        Assert.Equal(3, Value("--x", 3));
        Assert.Equal(19, Value("1+2*3^2", 0));
    }

    /// <summary>
    /// IEEE 754-2019 §9.2: <c>pow(1, y)</c> is 1 for every y, NaN included, and
    /// <c>pow(±1, ±∞)</c> is 1. Swift's C <c>pow</c> answers so; JavaScript and
    /// Java return NaN for all five and their ports wrap. The wrapper here is
    /// unconditional, so these pin the evaluator and never the CRT underneath.
    /// </summary>
    [Fact]
    public void ExpressionLanguagePowerIsIEEECorrectForTheUnitBaseCases()
    {
        Assert.True(double.IsNaN(Value("0/0", 0)), "0/0 is the NaN these rows are built from");
        Assert.Equal(1.0, Value("pow(1, 0/0)", 0));
        Assert.Equal(1.0, Value("pow(1, 1/0)", 0));
        Assert.Equal(1.0, Value("pow(1, -1/0)", 0));
        Assert.Equal(1.0, Value("pow(-1, 1/0)", 0));
        Assert.Equal(1.0, Value("pow(-1, -1/0)", 0));
        // `^` routes to the same pow, so it must agree row for row.
        Assert.Equal(1.0, Value("1^(0/0)", 0));
        Assert.Equal(1.0, Value("1^(1/0)", 0));
        Assert.Equal(1.0, Value("1^(-1/0)", 0));
        Assert.Equal(1.0, Value("(-1)^(1/0)", 0));
        Assert.Equal(1.0, Value("(-1)^(-1/0)", 0));
    }

    /// <summary>The TypeScript suite's neighbours: everything next to the five special cases is left exactly as the platform has it.</summary>
    [Fact]
    public void ExpressionLanguagePowerLeavesEveryNeighbouringCaseAlone()
    {
        Assert.Equal(1.0, Value("pow(0/0, 0)", 0));
        Assert.Equal(1.0, Value("(0/0)^0", 0));
        Assert.True(double.IsNaN(Value("pow(-1, 0/0)", 0)));
        Assert.True(double.IsNaN(Value("pow(2, 0/0)", 0)));
        Assert.Equal(double.PositiveInfinity, Value("pow(2, 1/0)", 0));
        Assert.Equal(double.PositiveInfinity, Value("(-1.0000001)^(1/0)", 0));
        Assert.Equal(0.0, Value("(-1.0000001)^(-1/0)", 0));
        Assert.Equal(1.0, Value("0^0", 0));
        Assert.Equal("43e0000000000000", Bits(Value("2^63", 0)));
        Assert.True(double.IsNaN(Value("(-8)^0.5", 0)));
        Assert.Equal("3ff6a09e667f3bcd", Bits(Value("pow(2,x)", 0.5)));
        Assert.Equal("3ff6a09e667f3bcd", Bits(Value("2^0.5", 0)));
        Assert.Equal("3ff6a09e667f3bcd", Bits(Value("exp2(x)", 0.5)));
        Assert.Equal("401d8e64b8d4ddad", Bits(Value("e^2", 0)));
        Assert.Equal(9, Value("pow(x,2)", 3));
    }

    [Fact]
    public void ExpressionLanguageKnowsPiAndENothingElseWithoutParentheses()
    {
        Assert.Equal(Math.PI, Value("pi", 0));
        Assert.Equal("400921fb54442d18", Bits(Value("pi", 0)));
        Assert.Equal(Math.E, Value("e", 0));
        Assert.Equal("4005bf0a8b145769", Bits(Value("e", 0)));
        Assert.Equal(7.3890560989306495, Value("e^2", 0));
        AssertPlotError(() => Value("sin", 0), "sin is a function");
        // U+2014 EM DASH and U+2026 HORIZONTAL ELLIPSIS, as every port spells it.
        Assert.Equal("sin is a function — write sin(…)", AssertPlotError(() => Value("sin", 0), "").Message);
    }

    /// <summary>The operators' edge semantics the report pins: fmod-style <c>%</c>, IEEE comparisons, NaN truthiness.</summary>
    [Fact]
    public void ExpressionLanguageEvaluatesRemainderComparisonsAndTruthAsEveryPortDoes()
    {
        Assert.Equal(-1, Value("-7%3", 0));
        Assert.Equal(1, Value("7%-3", 0));
        Assert.Equal(1.5, Value("5.5%2", 0));
        Assert.True(double.IsNaN(Value("1%0", 0)));
        Assert.Equal(double.NegativeInfinity, Value("-1/0", 0));
        Assert.Equal(1, Value("(0/0)&&1", 0));          // NaN != 0 is true: NaN is truthy here
        Assert.Equal(0, Value("(0/0)==(0/0)", 0));
        Assert.Equal(1, Value("(0/0)!=(0/0)", 0));
        Assert.Equal(0, Value("!(0/0)", 0));
        Assert.Equal(1, Value("0||1", 0));
        Assert.Equal(0, Value("0||0", 0));
        Assert.Equal(2, Value("floor(x)", 2.7));
        Assert.Equal(-2, Value("ceil(x)", -2.5));
        Assert.Equal(1, Value("round(x)", 0.5));
        Assert.Equal(-3, Value("round(x)", -2.5));
        Assert.Equal(0, Value("round(x)", 0.49999999999999994));   // not floor(v + 0.5)
        Assert.Equal(2, Value("cbrt(8)", 0));
        Assert.Equal(-2, Value("cbrt(-8)", 0));
        Assert.Equal(5, Value("hypot(3,4)", 0));
        Assert.Equal(5, Value("hypot(-5,0)", 0));
    }

    // MARK: - §4 The four corrected behaviours, as figures

    /// <summary>Everything a rendered figure can be asked about without an XML parser.</summary>
    private sealed record Facts(int Lines, int Texts, int Polylines, string? First, string? Last,
        string[] XLabels, string[] YLabels);

    private static readonly Regex RunPattern = new("<polyline points=\"([^\"]*)\"", RegexOptions.CultureInvariant);
    private static readonly Regex LinePattern = new("<line ", RegexOptions.CultureInvariant);
    private static readonly Regex TextPattern = new("<text ", RegexOptions.CultureInvariant);
    private static readonly Regex XLabelPattern = new("text-anchor=\"middle\">([^<]*)</text>", RegexOptions.CultureInvariant);
    private static readonly Regex YLabelPattern = new("dominant-baseline=\"middle\">([^<]*)</text>", RegexOptions.CultureInvariant);
    private static readonly Regex EntityPattern = new("&[a-z]+;", RegexOptions.CultureInvariant);
    private static readonly Regex NumericAttribute = new(" (?:x|y|x1|y1|x2|y2|width|height|cx|cy)=\"([^\"]*)\"", RegexOptions.CultureInvariant);
    private static readonly Regex PointsAttribute = new("points=\"([^\"]*)\"", RegexOptions.CultureInvariant);
    private static readonly Regex RectPattern = new("<rect x=\"([\\d.]+)\" y=\"([\\d.]+)\" width=\"([\\d.]+)\" height=\"([\\d.]+)\"", RegexOptions.CultureInvariant);

    private static string[] Captures(Regex pattern, string text)
    {
        var out_ = new List<string>();
        foreach (Match match in pattern.Matches(text)) out_.Add(match.Groups[1].Value);
        return out_.ToArray();
    }

    private static Facts FactsOf(string svg)
    {
        var runs = Captures(RunPattern, svg);
        string? first = null;
        string? last = null;
        if (runs.Length > 0)
        {
            first = runs[0].Split(' ')[0];
            var lastRun = runs[runs.Length - 1].Split(' ');
            last = lastRun[lastRun.Length - 1];
        }
        return new Facts(LinePattern.Matches(svg).Count, TextPattern.Matches(svg).Count, runs.Length, first, last,
            Captures(XLabelPattern, svg), Captures(YLabelPattern, svg));
    }

    private static Facts Figure(string source) => FactsOf(Plot.PlotSvg(source));

    [Fact]
    public void Correction1FloorCeilAndRoundDrawACurveWhereTheSiteDrawsNothing()
    {
        // broken_floor_no_curve.svg has 0 polylines. Here the staircase is one
        // run: floor(x) stays inside [-2, 2] for x in [-2, 3), and every step
        // lands inside the window, so nothing breaks it.
        var floor = Figure("x: -10..10\ny: -2..2\nfloor(x)");
        Assert.Equal(1, floor.Polylines);
        Assert.Equal("248.00,360.00", floor.First);  // x = -2, y = -2: the bottom left
        Assert.Equal("377.48,40.00", floor.Last);    // x = 2.98, y = 2: the top of the last step
        Assert.True(Figure("x: -10..10\ny: -2..2\nceil(x)").Polylines > 0);
        Assert.True(Figure("x: -10..10\ny: -2..2\nround(x)").Polylines > 0);
    }

    [Fact]
    public void Correction2AComparisonIsANumberSoTheHalfDomainIdiomDraws()
    {
        // boolean_no_curve.svg has 0 polylines for `x>0`.
        var step = Figure("x: -10..10\ny: -2..2\nx>0");
        Assert.Equal(1, step.Polylines);
        Assert.Equal("40.00,200.00", step.First);   // 0 at the far left
        Assert.Equal("560.00,120.00", step.Last);   // 1 at the far right

        // The spec's own idiom: NaN times zero is still NaN, so the left half
        // stays empty and the curve begins at the origin.
        var half = Figure("x: -4..4\ny: -1..3\n(x>0)*sqrt(x)");
        Assert.Equal(1, half.Polylines);
        Assert.Equal("300.00,280.00", half.First);  // x = 0, y = 0
        Assert.Equal("560.00,120.00", half.Last);   // x = 4, y = 2

        // A rectifier, drawn from edge to edge, until it climbs out at y = 3.
        var relu = Figure("x: -4..4\ny: -1..3\n(x>0)*x");
        Assert.Equal(1, relu.Polylines);
        Assert.Equal("40.00,280.00", relu.First);
        Assert.Equal("495.00,40.00", relu.Last);
    }

    [Fact]
    public void Correction3PowerIsRightAssociativeInAFigureToo()
    {
        // A constant series is a flat line, so its height IS the value: with
        // y: 0..1024 the line at 512 lands exactly halfway.
        var chart = Figure("x: -1..1\ny: 0..1024\n2^3^2");
        Assert.Equal("40.00,200.00", chart.First);
        Assert.Equal("560.00,200.00", chart.Last);
    }

    [Fact]
    public void Correction4FiveOverTwoIsTwoAndAHalfWhereTheSiteDrawsItAtTwo()
    {
        // int_division_trunc.svg puts the line at y = 232, which is sy(2).
        var chart = Figure("x: -1..1\ny: 0..5\n5/2");
        Assert.Equal("40.00,200.00", chart.First);  // sy(2.5)
        Assert.Equal("560.00,200.00", chart.Last);
    }

    [Fact]
    public void AxisCorrectionLabelsATickAtMinusFourMinusFour()
    {
        // tick_label_truncation.svg, both axes [-5, -3]: the site's sixth label
        // reads "-3", out of order, in the middle of the axis.
        var chart = Figure("x: -5..-3\ny: -5..-3\nx");
        Assert.Equal("-4", chart.XLabels[5]);
        Assert.Equal("-4", chart.YLabels[5]);
        Assert.Equal(new[] { "-5", "-4.80", "-4.60", "-4.40", "-4.20", "-4", "-3.80", "-3.60", "-3.40", "-3.20", "-3" },
            chart.XLabels);
    }

    [Fact]
    public void AxisCorrectionLabelsTheTickAtTheOriginZero()
    {
        // tick_drift_zero_label.svg: `gx += step` over [-1, 1] at 0.2 never lands
        // on zero. `first + i * step` does.
        var chart = Figure("x: -1..1\ny: -1..1\nx");
        Assert.Equal("0", chart.XLabels[5]);
        Assert.Equal("0", chart.YLabels[5]);
        // And tick_drift_extra_tick.svg, where the drift is 1.4e-16 instead.
        Assert.Equal("0", Figure("x: -0.9..0.3\ny: -0.9..0.3\nx").XLabels[9]);
    }

    [Fact]
    public void AxisCorrectionKeepsTheTickThatLandsExactlyOnTheMaximum()
    {
        // `0.0001 + 8 * 0.0001` is 9.000000000000001e-4, a hair over the range's
        // own maximum; the site drops it (tiny_range.svg has eight ticks per axis).
        var chart = Figure("x: 0.0001..0.0009\ny: 0.0001..0.0009\nx");
        Assert.Equal(9, chart.XLabels.Length);
        Assert.Equal("9.0e-4", chart.XLabels[8]);
    }

    // MARK: - §5 The 22 recorded figures

    /// <summary>What differs from the vector for a figure whose recorded shape is a corrected behaviour; everything unlisted is still asserted against the site's own numbers.</summary>
    private sealed record FigureFix(int? Polylines = null, string? First = null, string? Last = null,
        int? Lines = null, int? Texts = null, string[]? XLabels = null, string[]? YLabels = null);

    private static readonly string[] Drift =
        { "-1", "-0.80", "-0.60", "-0.40", "-0.20", "0", "0.20", "0.40", "0.60", "0.80", "1" };
    private static readonly string[] Truncated =
        { "-5", "-4.80", "-4.60", "-4.40", "-4.20", "-4", "-3.80", "-3.60", "-3.40", "-3.20", "-3" };
    private static readonly string[] TinyRange =
        { "1.0e-4", "2.0e-4", "3.0e-4", "4.0e-4", "5.0e-4", "6.0e-4", "7.0e-4", "8.0e-4", "9.0e-4" };
    private static readonly string[] DriftThirteen =
        { "-0.90", "-0.80", "-0.70", "-0.60", "-0.50", "-0.40", "-0.30", "-0.20", "-0.10", "0", "0.10", "0.20", "0.30" };

    private static readonly Dictionary<string, FigureFix> CorrectedFigures = new(StringComparer.Ordinal)
    {
        // floor(x) draws (correction 1).
        ["broken_floor_no_curve"] = new(Polylines: 1, First: "248.00,360.00", Last: "377.48,40.00"),
        // x>0 draws (correction 2).
        ["boolean_no_curve"] = new(Polylines: 1, First: "40.00,200.00", Last: "560.00,120.00"),
        // 5/2 is 2.5, and the origin's label is "0" and not "-5.6e-17".
        ["int_division_trunc"] = new(First: "40.00,200.00", Last: "560.00,200.00", XLabels: Drift),
        ["constant_three"] = new(XLabels: Drift),
        ["tick_drift_zero_label"] = new(XLabels: Drift, YLabels: Drift),
        ["tick_drift_extra_tick"] = new(XLabels: DriftThirteen, YLabels: DriftThirteen),
        // The truncated label, and the tick at the maximum the site's
        // accumulation overshot: eleven ticks per axis rather than ten.
        ["tick_label_truncation"] = new(Lines: 22, Texts: 22, XLabels: Truncated, YLabels: Truncated),
        ["no_zero_on_either_axis"] = new(Lines: 20, Texts: 20,
            XLabels: new[] { "1", "1.20", "1.40", "1.60", "1.80", "2", "2.20", "2.40", "2.60", "2.80", "3" }),
        ["tiny_range"] = new(Lines: 18, Texts: 18, XLabels: TinyRange, YLabels: TinyRange),
    };

    /// <summary>A range end, spelled the way the fence reads it back as the same double: whole numbers as integers, the rest shortest round-trip ("R", which is exact on .NET Core 3.0+).</summary>
    private static string FenceNumber(double v)
    {
        if (v == Math.Round(v) && Math.Abs(v) < 1e15) return ((long)v).ToString(Inv);
        return v.ToString("R", Inv);
    }

    [Fact]
    public void ThirteenOfTheRecordedFiguresAreDrawnExactlyAsTheSiteDoes()
    {
        Assert.Equal(22, V.Svg.Length);
        var same = 0;
        foreach (var row in V.Svg) if (!CorrectedFigures.ContainsKey(row.Name)) same += 1;
        Assert.Equal(13, same);
        // Every corrected name is a recorded figure — a fix for a figure that
        // does not exist is a claim about nothing.
        foreach (var name in CorrectedFigures.Keys) Assert.Contains(V.Svg, row => row.Name == name);
    }

    public static IEnumerable<object[]> RecordedFigureNames()
    {
        foreach (var row in V.Svg) yield return new object[] { row.Name };
    }

    [Theory]
    [MemberData(nameof(RecordedFigureNames))]
    public void TheRecordedFigure(string name)
    {
        SvgRow? found = null;
        foreach (var candidate in V.Svg) if (candidate.Name == name) found = candidate;
        var row = found!;
        var source = "x: " + FenceNumber(row.XMin) + ".." + FenceNumber(row.XMax) + "\n"
            + "y: " + FenceNumber(row.YMin) + ".." + FenceNumber(row.YMax) + "\n" + row.Expr;
        var got = FactsOf(Plot.PlotSvg(source));
        CorrectedFigures.TryGetValue(row.Name, out var fix);
        var label = row.Name + ": " + row.Expr;

        // The spacing is nice_step, ported verbatim: never corrected.
        Assert.True(Bits(row.XStep) == Bits(Plot.NiceStep(row.XMax - row.XMin)), label + " — x step");
        Assert.True(Bits(row.YStep) == Bits(Plot.NiceStep(row.YMax - row.YMin)), label + " — y step");

        Assert.True((fix?.Lines ?? row.LineCount) == got.Lines, label + " — grid + axis lines: " + got.Lines);
        Assert.True((fix?.Texts ?? row.TextCount) == got.Texts, label + " — tick labels: " + got.Texts);
        Assert.True((fix?.Polylines ?? row.PolylineCount) == got.Polylines, label + " — unbroken runs: " + got.Polylines);
        Assert.Equal(fix?.First ?? row.FirstPoint, got.First);
        Assert.Equal(fix?.Last ?? row.LastPoint, got.Last);
        Assert.Equal(fix?.XLabels ?? row.XTickLabels, got.XLabels);
        Assert.Equal(fix?.YLabels ?? row.YTickLabels, got.YLabels);
    }

    [Fact]
    public void BreaksACurveWhereItLeavesTheWindowAndNowhereElse()
    {
        // tan(x) over [-10, 10] is seven branches; 1/x over [-5, 5] is two; a
        // single plottable sample is still a polyline of one point.
        Assert.Equal(7, Figure("x: -10..10\ny: -2..2\ntan(x)").Polylines);
        Assert.Equal(2, Figure("x: -5..5\ny: -5..5\n1/x").Polylines);
        Assert.Equal("300.00,200.00", Figure("x: -10..10\ny: -0.005..0.005\nx").First);
        Has(Plot.PlotSvg("x: -10..10\ny: -0.005..0.005\nx"), "<polyline points=\"300.00,200.00\"");
    }

    [Fact]
    public void SamplesWithTheFormulaTheSiteUsesNotTheCheaperOne()
    {
        // `xMin + (i / samples) * span`, never `xMin + i * dx`: the two differ in
        // the last bits for 221 of the 1001 default samples, and the difference
        // reaches the output.
        var chart = Figure("x: -6.3..0.7999999999999998\ny: -3.3..3.1\nx");
        Assert.Equal("259.96,359.83", chart.First);
        Assert.Equal("560.00,155.00", chart.Last);
    }

    // MARK: - §6 The fence

    [Fact]
    public void FenceReadsDirectivesInAnyOrderAndIgnoresBlanksAndComments()
    {
        var spec = Plot.ParsePlot(Lines("# a comment", "", "sin(x)", "title: A title", "x: -1..1", "y: -2..2", ""));
        Assert.Equal("A title", spec.Title);
        Assert.Equal(-1, spec.XMin);
        Assert.Equal(1, spec.XMax);
        Assert.Equal(-2.0, spec.YMin);
        Assert.Equal(2.0, spec.YMax);
        Assert.Single(spec.Series);
        Assert.True(spec.HasDirectives);
    }

    [Fact]
    public void FenceTreatsAnUnknownKeyLineAsALabelledSeriesNotAnError()
    {
        // `f: x` still plots: the directive scan checks the key against the known
        // list before it claims the line, and the series parser then reads the
        // key as a label.
        var spec = Plot.ParsePlot("f: x");
        Assert.Single(spec.Series);
        Assert.Equal("f", spec.Series[0].Label);
        Assert.Equal("x", spec.Series[0].Source);
        Assert.False(spec.HasDirectives);
        Has(Plot.PlotSvg("f: sin(x)"), "<polyline");
    }

    [Fact]
    public void FenceDefaultsToTheSitesGeometry()
    {
        var spec = Plot.ParsePlot("sin(x)");
        Assert.Equal(-10, spec.XMin);
        Assert.Equal(10, spec.XMax);
        Assert.Null(spec.YMin);
        Assert.Null(spec.YMax);
        Assert.Equal(600, spec.Width);
        Assert.Equal(400, spec.Height);
        Assert.Equal(1000, spec.Samples);
        Assert.Equal(Plot.Legend.Auto, spec.Legend);
        Assert.True(spec.Grid);
        Assert.True(spec.Axes);
        Assert.Equal("", spec.Title);
        Assert.Equal("", spec.XLabel);
        Assert.Equal("", spec.YLabel);
    }

    [Fact]
    public void FenceClampsWidthHeightAndSamples()
    {
        var small = Plot.ParsePlot("width: 10\nheight: 10\nsamples: 1\nx");
        Assert.Equal(160, small.Width);
        Assert.Equal(120, small.Height);
        Assert.Equal(50, small.Samples);
        var large = Plot.ParsePlot("width: 9000\nheight: 9000\nsamples: 90000\nx");
        Assert.Equal(2000, large.Width);
        Assert.Equal(2000, large.Height);
        Assert.Equal(5000, large.Samples);
        // Rounded, ties away from zero — never banker's.
        Assert.Equal(201, Plot.ParsePlot("width: 200.5\nx").Width);
        Assert.Equal(200, Plot.ParsePlot("width: 200.4\nx").Width);
    }

    [Fact]
    public void FenceTakesAConstantExpressionAtEitherEndOfARange()
    {
        var spec = Plot.ParsePlot("x: -pi..2*pi\nsin(x)");
        Assert.Equal(-Math.PI, spec.XMin);
        Assert.Equal(2 * Math.PI, spec.XMax);
        // With no free name allowed, a range that mentions `x` is an error, not zero.
        AssertPlotError(() => Plot.ParsePlot("x: x..1\nx"), "unknown name 'x'");
    }

    [Fact]
    public void FenceRejectsARangeThatDoesNotIncrease()
    {
        AssertPlotError(() => Plot.ParsePlot("x: 1..1\nx"), "x range must be increasing");
        AssertPlotError(() => Plot.ParsePlot("y: 5..-5\nx"), "y range must be increasing");
        AssertPlotError(() => Plot.ParsePlot("x: nonsense\nx"), "");
        AssertPlotError(() => Plot.ParsePlot("x: 1\nx"), "x range must be written min..max");
        AssertPlotError(() => Plot.ParsePlot("x: ..1\nx"), "x range must be written min..max");
        AssertPlotError(() => Plot.ParsePlot("x: 1/0..2\nx"), "x range must be finite");
        // The FIRST `..` splits: `1...2` is min "1", max ".2".
        AssertPlotError(() => Plot.ParsePlot("x: 1...2\nx"), "x range must be increasing");
    }

    [Fact]
    public void FenceSplitsALabelOffTheFirstTopLevelBareEquals()
    {
        Assert.Equal("envelope", Plot.ParsePlot("envelope = exp(-abs(x)/5)").Series[0].Label);
        Assert.Equal("exp(-abs(x)/5)", Plot.ParsePlot("envelope = exp(-abs(x)/5)").Series[0].Source);
        // The FIRST one, so what follows still has to be an expression: there is
        // no assignment in the language for a second `=` to be part of.
        AssertPlotError(() => Plot.ParsePlot("a = b = x"), "unexpected character '='");
        // …and never off a comparison operator.
        foreach (var source in new[] { "x == 1", "x <= 1", "x >= 1", "x != 1" })
        {
            Assert.Null(Plot.ParsePlot(source).Series[0].Label);
        }
        // An `=` inside parentheses is not top-level, so it is the parser's problem, not a label.
        AssertPlotError(() => Plot.ParsePlot("(a = x)"), "unexpected character '='");
        Assert.Null(Plot.ParsePlot("= x").Series[0].Label);
        AssertPlotError(() => Plot.ParsePlot("label ="), "a series needs an expression");
    }

    [Fact]
    public void FenceReadsAPointsSeriesAndAParametricSeries()
    {
        var points = Plot.ParsePlot("measured = points: 0,0 1,2 2,1").Series[0];
        Assert.Equal(Plot.SeriesKind.Points, points.Kind);
        Assert.Equal("measured", points.Label);
        Assert.Equal(new[] { new Plot.Point(0, 0), new Plot.Point(1, 2), new Plot.Point(2, 1) }, points.Points);
        Assert.Equal("", points.Parameter);

        var parametric = Plot.ParsePlot("circle = (cos(t), sin(t)) for t in 0..2*pi").Series[0];
        Assert.Equal(Plot.SeriesKind.Parametric, parametric.Kind);
        Assert.Equal("t", parametric.Parameter);
        Assert.Equal(0, parametric.TMin);
        Assert.Equal(2 * Math.PI, parametric.TMax);
        Assert.NotNull(parametric.Expression);
        Assert.NotNull(parametric.YExpression);
        // The parametric variable is the only free name inside it: `x` is not.
        AssertPlotError(() => Plot.ParsePlot("(x, sin(t)) for t in 0..1"), "unknown name 'x'");
        AssertPlotError(() => Plot.ParsePlot("(cos(t), sin(t)) for u in 0..1"), "unknown name 't'");
        // The errors the grammar names, verbatim.
        AssertPlotError(() => Plot.ParsePlot("(cos(t)) for t in 0..1"), "a parametric series needs (x(t), y(t))");
        AssertPlotError(() => Plot.ParsePlot("(cos(t), sin(t)) for 1 in 0..1"), "expected a parameter name after 'for'");
        AssertPlotError(() => Plot.ParsePlot("(cos(t), sin(t)) for t on 0..1"), "expected 'in' after 't'");
        AssertPlotError(() => Plot.ParsePlot("(cos(t), sin(t)) for t in 1..0"), "t range must be increasing");
        // Points: case-insensitive prefix, each coordinate a constant expression.
        Assert.Equal(Plot.SeriesKind.Points, Plot.ParsePlot("POINTS: pi,2*e").Series[0].Kind);
        Assert.Equal(Math.PI, Plot.ParsePlot("POINTS: pi,2*e").Series[0].Points[0].X);
        AssertPlotError(() => Plot.ParsePlot("points: 1 2"), "points must be x,y pairs — '1' is not one");
        AssertPlotError(() => Plot.ParsePlot("points: 1,"), "point range must be written min..max");
        // `points:` alone is a points line with no pairs, not an empty body.
        AssertPlotError(() => Plot.ParsePlot("points:"), "points needs at least one x,y pair");
        AssertPlotError(() => Plot.ParsePlot("points ="), "a series needs an expression");
        AssertPlotError(() => Plot.ParsePlot("points: 1/0,1"), "point range must be finite");
        // `points : 1,2` (space before the colon) is a labelled series `points`, whose body fails to parse.
        AssertPlotError(() => Plot.ParsePlot("points : 1,2"), "unexpected ','");
        // A points series draws its polyline and then a circle per point.
        var svg = Plot.PlotSvg("x: 0..2\ny: 0..2\npoints: 0,0 1,2 2,1");
        Has(svg, "<polyline points=\"40.00,360.00 300.00,40.00 560.00,200.00\"");
        Has(svg, "<circle cx=\"40.00\" cy=\"360.00\" r=\"2.5\" fill=\"#673AB7\"/><circle cx=\"300.00\" cy=\"40.00\"");
        Assert.True(svg.IndexOf("<circle", StringComparison.Ordinal) > svg.IndexOf("<polyline", StringComparison.Ordinal));
    }

    [Fact]
    public void FenceDoesNotMistakeAParenthesisedExpressionForAParametricOne()
    {
        Assert.Equal(Plot.SeriesKind.Function, Plot.ParsePlot("(x+1)*2").Series[0].Kind);
        Assert.Equal("x", Plot.ParsePlot("(x+1)*2").Series[0].Parameter);
        // A pair with no `for` is not a parametric series, so it is read as an
        // expression — and a tuple is not one of those.
        AssertPlotError(() => Plot.ParsePlot("(x, x)"), "expected ')'");
        // `(x) format` — a match followed by a word that merely starts with `for`.
        AssertPlotError(() => Plot.ParsePlot("(x) format"), "unexpected 'format'");
    }

    [Fact]
    public void FenceFitsYAutoToTheFiniteSamplesWithFivePercentOfPadding()
    {
        // sin over a whole period reaches ±1, so the window is 1.05 either way.
        Has(Plot.PlotSvg("x: -10..10\nsin(x)"), ">1</text>");
        // A series with nothing finite in it falls back to -1..1.
        Has(Plot.PlotSvg("x: -10..10\nsqrt(-1)+x*0"), ">1</text>");
        // A flat series has no span to take 5 % of: it is padded by 5 % of itself.
        Assert.Single(Plot.ParsePlot("x: -1..1\n3").Series);
        Has(Plot.PlotSvg("x: -1..1\n3"), "<polyline");
        // 2.85..3.15: the flat line sits exactly halfway.
        Assert.Equal("40.00,200.00", Figure("x: -1..1\n3").First);
        // `y: auto` spelt out is the default, in any case.
        Assert.Null(Plot.ParsePlot("y: AUTO\nx").YMin);
        Assert.True(Plot.ParsePlot("y: auto").HasDirectives);
    }

    [Fact]
    public void FenceShowsTheLegendForTwoSeriesOrOneThatIsLabelled()
    {
        Lacks(Plot.PlotSvg("x: -1..1\nsin(x)"), "font-size=\"11\" font-family=\"sans-serif\"");
        Has(Plot.PlotSvg("x: -1..1\nsin(x)\ncos(x)"), "font-size=\"11\" font-family=\"sans-serif\"");
        Has(Plot.PlotSvg("x: -1..1\nwave = sin(x)"), ">wave</text>");
        Lacks(Plot.PlotSvg("x: -1..1\nlegend: off\nsin(x)\ncos(x)"), "font-size=\"11\" font-family=\"sans-serif\"");
        // An unlabelled series' legend text is its own source.
        Has(Plot.PlotSvg("x: -1..1\nlegend: on\nsin(x)"), ">sin(x)</text>");
        AssertPlotError(() => Plot.ParsePlot("legend: maybe\nx"), "legend must be 'on', 'off' or 'auto'");
        Assert.Equal(Plot.Legend.On, Plot.ParsePlot("legend: ON\nx").Legend);
    }

    [Fact]
    public void FenceTurnsTheGridAndTheAxesOff()
    {
        var bare = Plot.PlotSvg("x: -1..1\ngrid: off\naxes: off\nx");
        Lacks(bare, "<line");
        Lacks(bare, "<text x=");
        Lacks(bare, "<rect");
        Has(bare, "<polyline");
        AssertPlotError(() => Plot.ParsePlot("grid: sometimes\nx"), "grid must be 'on' or 'off'");
        AssertPlotError(() => Plot.ParsePlot("axes: 1\nx"), "axes must be 'on' or 'off'");
        // The axes group is emitted even when no axis crosses the window.
        Has(Plot.PlotSvg("x: 1..3\ny: 1..9\nx"), "<g stroke=\"currentColor\" stroke-width=\"1\" opacity=\"0.4\"></g>");
    }

    [Fact]
    public void FenceGivesEachSeriesTheNextColourPurpleFirst()
    {
        var svg = Plot.PlotSvg("x: -1..1\nx\nx+0.1\nx+0.2");
        Has(svg, "stroke=\"#673AB7\"");
        Has(svg, "stroke=\"#E5390F\"");
        Has(svg, "stroke=\"#0F9D58\"");
        // Eight colours, then round again.
        var nine = Plot.PlotSvg("x: -1..1\nx\nx+1\nx+2\nx+3\nx+4\nx+5\nx+6\nx+7\nx+8");
        foreach (var colour in new[] { "#673AB7", "#E5390F", "#0F9D58", "#F4B400", "#00838F", "#C2185B", "#5D4037", "#455A64" })
        {
            Has(nine, "stroke=\"" + colour + "\"");
        }
        Assert.Equal(2, Regex.Matches(nine, "<polyline points=\"[^\"]*\" fill=\"none\" stroke=\"#673AB7\"", RegexOptions.CultureInvariant).Count);
    }

    /// <summary>The grammar's own whitespace and line breaks — where <c>string.Trim()</c>, <c>char.IsWhiteSpace</c> and <c>Split</c> would each read a different fence.</summary>
    [Fact]
    public void FenceTrimsOnlySpaceAndTabAndBreaksLinesOnlyOnCrLf()
    {
        // NBSP is not trimmed from a value, and is an unexpected character in an expression.
        Assert.Equal("\u00A0T\u00A0", Plot.ParsePlot("title: \u00A0T\u00A0").Title);
        Assert.Equal("T", Plot.ParsePlot("\t title:\t T \t").Title);
        AssertPlotError(() => Plot.ParsePlot("x\u00A0+ 1"), "unexpected character '\u00A0'");
        // CRLF and bare CR are line breaks; U+2028 is not.
        Assert.Equal(2, Plot.ParsePlot("x: -1..1\r\nsin(x)\rcos(x)").Series.Count);
        AssertPlotError(() => Plot.ParsePlot("sin(x)\u2028cos(x)"), "unexpected character '\u2028'");
        // A trailing line break yields an empty last line, which is skipped.
        Assert.Single(Plot.ParsePlot("sin(x)\n").Series);
        // Keys are ASCII lowercase and `-` only: `Title:` and `f2:` are expressions, `x :` is keyed.
        AssertPlotError(() => Plot.ParsePlot("Title: x"), "unexpected character ':'");
        AssertPlotError(() => Plot.ParsePlot("f2: x"), "unexpected character ':'");
        Assert.Equal(1, Plot.ParsePlot("x : 1..2\nx").XMin);
        // A comment is a `#` first after the trim.
        Assert.Empty(Plot.ParsePlot("   # sin(x)").Series);
        // Directive values go through the constant grammar: names are errors, ∞ is refused by name.
        AssertPlotError(() => Plot.ParsePlot("width: abc\nx"), "unknown name 'abc'");
        AssertPlotError(() => Plot.ParsePlot("width: 1/0\nx"), "width must be a number");
        AssertPlotError(() => Plot.ParsePlot("samples:\nx"), "the expression ends too early");
    }

    /// <summary>The legend gutter counts code points, so an emoji label reserves the same room as a one-letter label — <c>string.Length</c> would move the frame.</summary>
    [Fact]
    public void FenceMeasuresLegendLabelsInCodePointsNotUtf16Units()
    {
        var emoji = Plot.PlotSvg("x: -1..1\n\U0001F600 = x");
        var letter = Plot.PlotSvg("x: -1..1\na = x");
        Assert.Equal(RectPattern.Match(letter).Value, RectPattern.Match(emoji).Value);
        Has(emoji, ">\U0001F600</text>");
        // A wider label really does widen the gutter.
        Assert.NotEqual(RectPattern.Match(letter).Value, RectPattern.Match(Plot.PlotSvg("x: -1..1\nabcdefghijkl = x")).Value);
        // The unexpected-character message names the whole code point, not half of it.
        Has(Plot.RenderPlot("x \U0001F600"), "unexpected character '\U0001F600'");
    }

    // MARK: - §7 The container, and what must never be in it

    [Fact]
    public void MarkupIsADivPlotAroundOneSvgWithAViewBox()
    {
        var block = Plot.RenderPlot("x: -10..10\nsin(x)");
        StartsWith(block, "<div class=\"plot\"><svg ");
        EndsWith(block, "</svg></div>");
        // Without a viewBox, `max-width: 100%; height: auto` shrinks the box and
        // clips the drawing instead of scaling it.
        Has(block, "viewBox=\"0 0 600 400\"");
        Has(block, "width=\"600\" height=\"400\" role=\"img\"");
        Assert.Equal("<div class=\"plot\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 600 400\" width=\"600\" height=\"400\" role=\"img\"><title>Plot of sin(x)</title>",
            block.Substring(0, block.IndexOf("</title>", StringComparison.Ordinal) + "</title>".Length));
    }

    [Fact]
    public void MarkupCarriesNoIdAtAll()
    {
        // A duplicated id is how one figure ends up wearing another's clip path
        // once a document holds two plots. An <svg role="img"> is named by its
        // own <title>, with no aria-labelledby to point at.
        var two = Plot.RenderPlot("sin(x)") + Plot.RenderPlot("cos(x)");
        Lacks(two, " id=");
        Lacks(two, "aria-labelledby");
        Has(Plot.PlotSvg("x: -10..10\ntitle: T\nsin(x)"), "<title>T</title>");
        Has(Plot.PlotSvg("sin(x)"), "<title>Plot of sin(x)</title>");
        Has(Plot.PlotSvg("a = sin(x)\ncos(x)"), "<title>Plot of a, cos(x)</title>");
        Has(Plot.PlotSvg("x: -1..1"), "<title>Plot</title>");
    }

    [Fact]
    public void MarkupPaintsWithCurrentColorAndBakesOnlyTheSeriesColours()
    {
        var svg = Plot.PlotSvg("x: -10..10\ntitle: T\nsin(x)");
        Has(svg, "stroke=\"currentColor\"");
        Has(svg, "fill=\"currentColor\"");
        foreach (var grey in new[] { "#e0e0e0", "#999", "#666", "#ccc" }) Lacks(svg, grey, grey);
        Lacks(svg, "background:white");
        Has(svg, "stroke=\"#673AB7\"");
    }

    [Fact]
    public void MarkupEmbedsNoStyleScriptForeignObjectOrFont()
    {
        // An SVG <style> inside an HTML document is document-scoped and leaks.
        var svg = Plot.PlotSvg("x: -10..10\ntitle: T\nsin(x)");
        foreach (var forbidden in new[] { "<style", "<script", "<foreignObject", "@font-face", "<image" })
        {
            Lacks(svg, forbidden, forbidden);
        }
    }

    [Fact]
    public void MarkupXMLEscapesEveryAuthorStringWithTheFourEntitiesAndNoOther()
    {
        // The EPUB body is XHTML, which is XML: one raw `&` makes the whole
        // content document unparseable. Four entities, not five: `&apos;` is
        // never emitted (the reference escapes exactly these four, and the
        // byte-parity golden depends on it), and never a named entity like
        // `&nbsp;`, undefined in XML.
        var hostile = Plot.PlotSvg(Lines("title: A & B <c> \"d\" 'e'", "xlabel: <x>", "ylabel: &y;", "p & q = x"));
        Has(hostile, "<title>A &amp; B &lt;c&gt; &quot;d&quot; 'e'</title>");
        Has(hostile, ">&lt;x&gt;</text>");
        Has(hostile, ">&amp;y;</text>");
        Has(hostile, ">p &amp; q</text>");
        Lacks(hostile, "&nbsp;");
        Lacks(hostile, "&apos;");
        foreach (Match entity in EntityPattern.Matches(hostile))
        {
            Assert.Contains(entity.Value, new[] { "&amp;", "&lt;", "&gt;", "&quot;" });
        }
        // `&` followed by a combining mark is still caught — a per-code-unit pass, never a grapheme one.
        Has(Plot.PlotSvg("title: &\u0301\nx"), "<title>&amp;\u0301</title>");
    }

    /// <summary>The Kotlin suite's guard, plot-local: the container parses as XML, and the hostile title reads back as the author wrote it.</summary>
    [Fact]
    public void MarkupIsWellFormedXmlWithAHostileTitle()
    {
        var block = Plot.RenderPlot(Lines("x: -10..10", "title: A & B <c> \"d\" 'e'", "xlabel: <x>", "ylabel: &y;", "p & q = sin(x)"));
        var document = XDocument.Parse(block);
        XNamespace svg = "http://www.w3.org/2000/svg";
        Assert.Equal("div", document.Root!.Name.LocalName);
        Assert.Single(document.Descendants(svg + "svg"));
        Assert.Equal("A & B <c> \"d\" 'e'", document.Descendants(svg + "title").First().Value);
        Assert.Single(document.Descendants(svg + "polyline"));
        // And the fallback container too.
        var broken = XDocument.Parse(Plot.RenderPlot("<b>&</b>"));
        // `<` and `>` tokenize as operators; `&` is the first character that is none, and the
        // tokenizer runs over the whole text before the parser sees any of it.
        Assert.Equal("plot: unexpected character '&'\n<b>&</b>", broken.Root!.Element("pre")!.Value);
    }

    [Fact]
    public void MarkupEmitsTheContainerEvenForAnEmptyBlockAndABrokenOne()
    {
        // If it is ever omitted the SVG-export ordinals desynchronise and every
        // later diagram exports the wrong figure.
        Assert.Equal("<div class=\"plot\"></div>", Plot.RenderPlot(""));
        Assert.Equal("<div class=\"plot\"></div>", Plot.RenderPlot("# only a comment"));
        Assert.Equal("<div class=\"plot\"></div>", Plot.RenderPlot("   "));
        var broken = Plot.RenderPlot("sinc(x)");
        StartsWith(broken, "<div class=\"plot\"><pre>");
        Has(broken, "plot: unknown function 'sinc'");
        Has(broken, "sinc(x)");  // the source always stays visible
        Assert.Equal("<div class=\"plot\"><pre>plot: unknown function 'sinc'\nsinc(x)</pre></div>", broken);
        Has(Plot.RenderPlot("x: 1..1\nx"), "plot: x range must be increasing");
    }

    [Fact]
    public void MarkupEscapesTheSourceItFallsBackTo()
    {
        Has(Plot.RenderPlot("<b>&</b>"), "&lt;b&gt;&amp;&lt;/b&gt;");
    }

    [Fact]
    public void MarkupNeverReturnsAnythingButAContainerWhateverItIsHanded()
    {
        // Whatever a fence contains, the answer is a div.plot with either a
        // drawing or the source in it, and every coordinate in that drawing is a
        // real number. The resource guards keep the deep and the long ones out
        // of the recursion — a .NET StackOverflowException cannot be caught.
        var hostile = new[]
        {
            "", "   ", "#", "x: 0..0\nx", "y: 1..0\nx", "width: -5\nheight: abc\nx",
            "points:", "points: 1", "label =", "= x", "(cos(t), sin(t)) for t in 0..0",
            "(cos(t), sin(t)) for u in 0..1", "x: 1e308..-1e308\nx", "x: -1e308..1e308\nx",
            "x: 0.0000001..0.0000002\nx", "axes: off\ngrid: off\nx", "ln(x)", "x^x",
            "sqrt(-x)", "0/0", "x*0/0", Repeat("(", 200) + "x",
            "title: " + Repeat("A", 500) + "\nx",
            "y: -1..1\n" + Repeat("sin(x)\n", 12),
            "x: -1..1\n1e400", "x: -1e400..1\nx", "samples: 1e400\nx", "\uD83D", "x: 1..2\n\uDE00",
        };
        foreach (var source in hostile)
        {
            var html = Plot.RenderPlot(source);
            StartsWith(html, "<div class=\"plot\">");
            EndsWith(html, "</div>");
            foreach (Match match in NumericAttribute.Matches(html))
            {
                var number = match.Groups[1].Value;
                Assert.True(double.TryParse(number, NumberStyles.Float, Inv, out var parsed) && double.IsFinite(parsed),
                    source + " → " + number);
            }
            foreach (Match match in PointsAttribute.Matches(html))
            {
                foreach (var pair in match.Groups[1].Value.Split(' '))
                {
                    var parts = pair.Split(',');
                    Assert.True(parts.Length == 2, pair);
                    foreach (var part in parts)
                    {
                        Assert.True(double.TryParse(part, NumberStyles.Float, Inv, out var parsed) && double.IsFinite(parsed), pair);
                    }
                }
            }
        }
    }

    [Fact]
    public void MarkupSurvivesAFigureSqueezedToTheSmallestCanvas()
    {
        // Title, both axis labels and a legend on a 160 × 120 canvas would compute
        // a negative plot area without fitMargins.
        var tiny = Plot.PlotSvg(Lines("width: 160", "height: 120", "title: T", "xlabel: x", "ylabel: y", "legend: on", "a = x"));
        Has(tiny, "viewBox=\"0 0 160 120\"");
        Lacks(tiny, "NaN");
        var rect = RectPattern.Match(tiny);
        Assert.True(rect.Success, "the plot area is still a real rectangle");
        var x = Literal(rect.Groups[1].Value);
        var y = Literal(rect.Groups[2].Value);
        var w = Literal(rect.Groups[3].Value);
        var h = Literal(rect.Groups[4].Value);
        Assert.True(w >= 40);
        Assert.True(h >= 40);
        Assert.True(x + w <= 160);
        Assert.True(y + h <= 120);
    }

    // MARK: - §9 The figure itself, byte for byte

    private static readonly string GoldenSource = Lines(
        "x: -10..10",
        "y: -2..2",
        "title: Damped oscillation",
        "xlabel: x",
        "ylabel: amplitude",
        "envelope = exp(-abs(x)/5)",
        "sin(x) * exp(-abs(x)/5)");

    [Fact]
    public void GoldenDrawsTheSpecsOwnExampleAsRecorded()
    {
        // The whole SVG of one document, pinned — the cross-port parity claim:
        // byte for byte the file md, md.macOS, md.Android and md.vscode all pin,
        // produced by the same fence. Compared as raw bytes including the
        // trailing newline, so an autocrlf checkout would fail loudly.
        var golden = File.ReadAllBytes(Fixture("golden", "plot-damped-oscillation.svg"));
        var drawn = Encoding.UTF8.GetBytes(Plot.RenderPlot(GoldenSource) + "\n");
        Assert.Equal(31647, golden.Length);
        Assert.True(golden.Length == drawn.Length, "byte count: " + drawn.Length);
        var firstDifference = -1;
        for (var index = 0; index < golden.Length; index++)
        {
            if (golden[index] != drawn[index]) { firstDifference = index; break; }
        }
        Assert.True(firstDifference < 0, "the figure is not byte-identical to the reference golden; first difference at byte "
            + firstDifference + ": …" + Encoding.UTF8.GetString(drawn, Math.Max(0, firstDifference - 40), Math.Min(80, drawn.Length - Math.Max(0, firstDifference - 40))) + "…");
        // The worked geometry, spelled out, so a break reads as a number and not a diff.
        var text = Encoding.UTF8.GetString(golden);
        Has(text, "<rect x=\"58.0\" y=\"64.0\" width=\"322.0\" height=\"278.0\"");
        Has(text, "transform=\"rotate(-90 14.0 203.0)\"");
        Has(text, "<polyline points=\"58.00,193.59 ");
        Has(text, "<polyline points=\"58.00,197.88 ");
        Has(text, "380.00,208.12\" fill=\"none\" stroke=\"#E5390F\"");
        Assert.Equal(2, RunPattern.Matches(text).Count);
        Assert.Equal(24, LinePattern.Matches(text).Count);
        Assert.Equal(25, TextPattern.Matches(text).Count);
    }

    // MARK: - §10 Resource limits and degenerate magnitudes

    [Fact]
    public void DrawsASeriesWhoseValuesOverflowThePaddedRange()
    {
        // `high - low` overflows for a series straddling ~1e308, which made every
        // sy() NaN and emitted points="40.00,NaN …".
        var out_ = Plot.RenderPlot("x: -10..10\nx*1e307");
        Lacks(out_, "NaN");
        Has(out_, "<polyline");
    }

    [Fact]
    public void LeavesAHugeButNarrowRangeExactlyAsAsked()
    {
        // The guard must fire on an overflowing WIDTH, not on a large bound:
        // [1.69e308, 1.71e308] is only 2e306 wide and is perfectly drawable.
        var out_ = Plot.RenderPlot("x: -1..1\ny: 1.69e308..1.71e308\n1.7e308");
        Lacks(out_, "NaN");
        Has(out_, "<polyline");
    }

    [Fact]
    public void ReportsDeepNestingAsAPlotLineNotAStackOverflow()
    {
        var source = "x: -1..1\n" + Repeat("(", 5000) + "x" + Repeat(")", 5000);
        Has(Plot.RenderPlot(source), "plot: expression nested too deeply");
    }

    [Fact]
    public void ReportsALongFlatChainTooWhichTheDepthGuardCannotSee()
    {
        // `x+x+x+…` parses at constant depth through the left-associative loop and
        // then overflows the stack in the evaluator, so depth alone is not enough.
        var source = "x: -1..1\nx" + Repeat("+x", 20000);
        Has(Plot.RenderPlot(source), "plot: expression too large");
    }

    [Fact]
    public void CapsTheSeriesCountTheOneInputWithNoClamp()
    {
        var lines = new List<string> { "x: -1..1" };
        for (var index = 1; index <= 1000; index++) lines.Add("x*" + index.ToString(Inv));
        Has(Plot.RenderPlot(string.Join("\n", lines)), "plot: too many series (limit 24)");
        // Twenty-four is fine.
        Assert.Equal(24, Plot.ParsePlot(string.Join("\n", lines.GetRange(0, 25))).Series.Count);
    }

    [Fact]
    public void DrawsTheAxesADirectivesOnlyBlockDescribes()
    {
        // Not an empty block: the author wrote three lines. Returning an empty
        // container would swallow them, and the family rule is never a hole.
        var out_ = Plot.RenderPlot("x: -10..10\ntitle: My chart\nylabel: y");
        Has(out_, "<svg");
        Has(out_, "My chart");
        Lacks(out_, "<polyline");
    }

    [Fact]
    public void StillDrawsNothingForAGenuinelyEmptyBlock()
    {
        Assert.Equal("<div class=\"plot\"></div>", Plot.RenderPlot(""));
        Assert.Equal("", Plot.PlotSvg("# only a comment"));
    }

    // MARK: - §11 The memo
    //
    // xUnit runs test classes in parallel and any class may render a plot, so
    // the exact statistics are pinned on a memo of this class's own through the
    // internal RenderPlot(source, memo) overload; the shared static gets a
    // smoke test only. Same code path, same bytes.

    private static string Fence(int index) => "x: -10..10\nsin(x) + " + index.ToString(Inv);

    [Fact]
    public void MemoServesARepeatRenderWithoutRedrawingIt()
    {
        var memo = new PlotMemo(32);
        var source = "x: -10..10\ntitle: T\nsin(x)";

        var first = Plot.RenderPlot(source, memo);
        Assert.Equal(new PlotMemo.Statistics(1, 0, 1), memo.Snapshot);

        var second = Plot.RenderPlot(source, memo);
        Assert.Equal(first, second);
        Assert.Equal(new PlotMemo.Statistics(1, 1, 1), memo.Snapshot);

        // A different fence is a different key — one keystroke's difference is a miss.
        _ = Plot.RenderPlot(source + " * 2", memo);
        Assert.Equal(new PlotMemo.Statistics(2, 1, 2), memo.Snapshot);
    }

    [Fact]
    public void MemoCachesFailuresToo()
    {
        // The state a fence spends most of its life in while it is being typed.
        var memo = new PlotMemo(32);
        var broken = "x: -10..10\nsinc(x)";
        var first = Plot.RenderPlot(broken, memo);
        Has(first, "plot: unknown function 'sinc'");
        var second = Plot.RenderPlot(broken, memo);
        Assert.Equal(first, second);
        Assert.Equal(new PlotMemo.Statistics(1, 1, 1), memo.Snapshot);
    }

    [Fact]
    public void MemoEvictsTheLeastRecentlyUsedEntryAtThirtyTwo()
    {
        var memo = new PlotMemo(32);
        for (var index = 0; index < 32; index++) _ = Plot.RenderPlot(Fence(index), memo);
        Assert.Equal(32, memo.Snapshot.Entries);
        Assert.Equal(32, memo.Snapshot.Misses);
        Assert.Equal(0, memo.Snapshot.Hits);

        // Touch 0 so it is the MOST recently used; 1 is then the oldest.
        _ = Plot.RenderPlot(Fence(0), memo);
        Assert.Equal(1, memo.Snapshot.Hits);

        // The 33rd entry evicts the least recently used, which is now 1 — not 0.
        _ = Plot.RenderPlot(Fence(32), memo);
        Assert.Equal(32, memo.Snapshot.Entries);

        var beforeProbe = memo.Snapshot;
        _ = Plot.RenderPlot(Fence(0), memo);
        Assert.Equal(beforeProbe.Hits + 1, memo.Snapshot.Hits);
        _ = Plot.RenderPlot(Fence(1), memo);
        Assert.Equal(beforeProbe.Misses + 1, memo.Snapshot.Misses);
        Assert.Equal(32, memo.Snapshot.Entries);
    }

    [Fact]
    public void MemoNeverConflatesTwoFencesThatDifferByACharacter()
    {
        var memo = new PlotMemo(32);
        var sine = Plot.RenderPlot("x: -1..1\nsin(x)", memo);
        var cosine = Plot.RenderPlot("x: -1..1\ncos(x)", memo);
        Assert.NotEqual(sine, cosine);
        Assert.Equal(new PlotMemo.Statistics(2, 0, 2), memo.Snapshot);
    }

    [Fact]
    public void MemoIsSafeToShareBetweenThreads()
    {
        // Not a race detector — a smoke test for the lock. The export paths build
        // their markup off the UI thread while the preview renders on it.
        var sources = new string[8];
        for (var i = 0; i < 8; i++) sources[i] = "x: -10..10\nsin(x) * " + (i + 1).ToString(Inv);
        var expected = new string[8];
        for (var i = 0; i < 8; i++) expected[i] = Plot.RenderPlot(sources[i], new PlotMemo(32));

        var memo = new PlotMemo(32);
        Parallel.For(0, 200, new ParallelOptions { MaxDegreeOfParallelism = 8 }, iteration =>
        {
            var index = iteration % sources.Length;
            Assert.Equal(expected[index], Plot.RenderPlot(sources[index], memo));
        });
        Assert.Equal(sources.Length, memo.Snapshot.Entries);
        Assert.Equal(200, memo.Snapshot.Hits + memo.Snapshot.Misses);
    }

    [Fact]
    public void MemoDoesNotChangeWhatTheRendererReturns()
    {
        // Cleared or warm, the golden fence is the same bytes — the one thing
        // that could silently break parity.
        var memo = new PlotMemo(32);
        var cold = Plot.RenderPlot(GoldenSource, memo);
        var warm = Plot.RenderPlot(GoldenSource, memo);
        memo.RemoveAll();
        Assert.Equal(new PlotMemo.Statistics(0, 0, 0), memo.Snapshot);
        var coldAgain = Plot.RenderPlot(GoldenSource, memo);
        Assert.Equal(cold, warm);
        Assert.Equal(cold, coldAgain);
        Assert.Equal(File.ReadAllBytes(Fixture("golden", "plot-damped-oscillation.svg")), Encoding.UTF8.GetBytes(warm + "\n"));
    }

    /// <summary>An oversized container is not memoised: the entry ceiling bounds the count, the length bound the bytes. Kotlin/TS bound in UTF-16 units and so does this port.</summary>
    [Fact]
    public void MemoDoesNotKeepAContainerLargerThanTheByteBound()
    {
        Assert.Equal(128 * 1024, PlotMemo.LargestMemoisedValue);
        var memo = new PlotMemo(32);
        var huge = Plot.RenderPlot("x: -1..1\nsamples: 5000\nx\nx+1\nx+2", memo);
        Assert.True(huge.Length > PlotMemo.LargestMemoisedValue, "the fence is meant to exceed the bound: " + huge.Length);
        Assert.Equal(new PlotMemo.Statistics(0, 0, 1), memo.Snapshot);
        var small = Plot.RenderPlot("x: -1..1\nx", memo);
        Assert.True(small.Length < PlotMemo.LargestMemoisedValue);
        Assert.Equal(new PlotMemo.Statistics(1, 0, 2), memo.Snapshot);
    }

    [Fact]
    public void MemoBehindTheStaticSurfaceIsTheSameMemo()
    {
        // The public hooks, with the weakest assertions that survive another
        // test class rendering a plot at the same time.
        Plot.ClearMemo();
        var source = "x: -10..10\ntitle: static memo\nsin(x)";
        var first = Plot.RenderPlot(source);
        var after = Plot.MemoStatistics;
        Assert.True(after.Entries >= 1 && after.Misses >= 1, after.ToString());
        Assert.Equal(first, Plot.RenderPlot(source));
        Assert.True(Plot.MemoStatistics.Hits >= after.Hits + 1 || Plot.MemoStatistics.Entries == 0,
            "a repeat render is served from the memo unless another class cleared it meanwhile");
    }
}
