using System.Diagnostics;
using System.Globalization;
using System.Text;
using System.Text.Json;
using Md.Core.Text;
using Xunit.Abstractions;

namespace Md.Core.Tests;

// SmartTyping against the shared oracle.
//
// Fixtures/typing-vectors.json is the cross-port contract for `enter` and `capitalize`:
// 1350 vectors (512 enter, 838 capitalize) generated by the TypeScript reference that
// docs/smart-typing.md was written against, copied verbatim into md, md.macOS, md.Android
// and here — exactly the arrangement plot-vectors.json has for the plotter. Every offset
// is a UTF-16 code unit; every unit outside U+0020–U+007E is a \uXXXX escape, so no editor
// can normalise an invisible character; `expected` is the JSON literal null, never the
// string "none" (that convention is the plot oracle's and Rust's Option).
//
// It is a specification, not a recording: no vector is skipped, none is "close enough",
// and a disputed one is changed in the JSON first, in one commit across the repos. The
// one place this port disagrees with the prose of the spec — .NET's invariant casing pins
// U+0131 to itself where the vector `cap-typed-dotless-i` wants `I` — is decided the
// vectors' way inside SmartTyping and documented there.
//
// Two shapes over the same corpus: one Theory per vector, keyed by id, so a failing case
// is named in the runner; and one Fact per array that walks every vector and reports all
// mismatches in a single message, which is what a port iterates on. The lone-surrogate
// behaviour (§0.9, §2.1a) cannot be a vector — Swift's JSONDecoder rejects an unpaired
// escape and a Swift String cannot hold one — so it is a native test here, as on Kotlin.
//
// Every string assertion here is ordinal, as in PlotTests: xUnit's Assert.Equal(string,
// string) is ordinal already, and the messages spell invisible units out.
public class SmartTypingTests
{
    private readonly ITestOutputHelper _output;

    public SmartTypingTests(ITestOutputHelper output)
    {
        _output = output;
    }

    // MARK: - The corpus

    private sealed record EnterVector(string Id, string Text, int Start, int End, SmartTyping.EnterEdit? Expected);

    private sealed record CapitalizeVector(string Id, string Text, int Start, int End, string Typed, string? Expected);

    private sealed record Vectors(int EnterCount, int CapitalizeCount, EnterVector[] Enter, CapitalizeVector[] Capitalize);

    /// <summary>
    /// Read once, with System.Text.Json: the escapes decode to the exact UTF-16 units the
    /// reference emitted (a surrogate-pair escape becomes one pair; an unpaired one would be
    /// rejected, which is why the generator refuses to write it).
    /// </summary>
    private static readonly Lazy<Vectors> Corpus = new(() =>
    {
        using var document = JsonDocument.Parse(File.ReadAllBytes(Fixtures.Path("typing-vectors.json")));
        var root = document.RootElement;
        var counts = root.GetProperty("_meta").GetProperty("counts");

        var enter = new List<EnterVector>();
        foreach (var row in root.GetProperty("enter").EnumerateArray())
        {
            var expected = row.GetProperty("expected");
            SmartTyping.EnterEdit? edit = expected.ValueKind == JsonValueKind.Null
                ? null
                : new SmartTyping.EnterEdit(
                    expected.GetProperty("location").GetInt32(),
                    expected.GetProperty("length").GetInt32(),
                    expected.GetProperty("replacement").GetString()!,
                    expected.GetProperty("caret").GetInt32());
            enter.Add(new EnterVector(row.GetProperty("id").GetString()!, row.GetProperty("text").GetString()!,
                row.GetProperty("start").GetInt32(), row.GetProperty("end").GetInt32(), edit));
        }

        var capitalize = new List<CapitalizeVector>();
        foreach (var row in root.GetProperty("capitalize").EnumerateArray())
        {
            var expected = row.GetProperty("expected");
            capitalize.Add(new CapitalizeVector(row.GetProperty("id").GetString()!, row.GetProperty("text").GetString()!,
                row.GetProperty("start").GetInt32(), row.GetProperty("end").GetInt32(),
                row.GetProperty("typed").GetString()!,
                expected.ValueKind == JsonValueKind.Null ? null : expected.GetString()));
        }

        return new Vectors(counts.GetProperty("enter").GetInt32(), counts.GetProperty("capitalize").GetInt32(),
            enter.ToArray(), capitalize.ToArray());
    });

    private static Vectors V => Corpus.Value;

    private static readonly Lazy<Dictionary<string, EnterVector>> EnterById = new(() =>
    {
        var map = new Dictionary<string, EnterVector>(StringComparer.Ordinal);
        foreach (var v in V.Enter) map.Add(v.Id, v);
        return map;
    });

    private static readonly Lazy<Dictionary<string, CapitalizeVector>> CapitalizeById = new(() =>
    {
        var map = new Dictionary<string, CapitalizeVector>(StringComparer.Ordinal);
        foreach (var v in V.Capitalize) map.Add(v.Id, v);
        return map;
    });

    public static IEnumerable<object[]> EnterIds()
    {
        foreach (var v in V.Enter) yield return [v.Id];
    }

    public static IEnumerable<object[]> CapitalizeIds()
    {
        foreach (var v in V.Capitalize) yield return [v.Id];
    }

    // MARK: - Rendering a mismatch

    /// <summary>A string with every unit outside printable ASCII written as <c>\uXXXX</c>, so a NBSP, a ZWSP or a CR is visible in a failure message.</summary>
    private static string Show(string? s)
    {
        if (s is null) return "null";
        var out_ = new StringBuilder(s.Length + 2);
        out_.Append('"');
        foreach (char c in s)
        {
            if (c == '\\') out_.Append("\\\\");
            else if (c == '"') out_.Append("\\\"");
            else if (c == '\n') out_.Append("\\n");
            else if (c >= 0x20 && c <= 0x7E) out_.Append(c);
            else out_.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
        }
        out_.Append('"');
        return out_.ToString();
    }

    private static string Show(SmartTyping.EnterEdit? e) => e is null
        ? "null"
        : "{location=" + e.Value.Location.ToString(CultureInfo.InvariantCulture)
            + ", length=" + e.Value.Length.ToString(CultureInfo.InvariantCulture)
            + ", replacement=" + Show(e.Value.Replacement)
            + ", caret=" + e.Value.Caret.ToString(CultureInfo.InvariantCulture) + "}";

    /// <summary>The mismatch for one enter vector, or null when it matches.</summary>
    private static string? CheckEnter(EnterVector v)
    {
        var actual = SmartTyping.Enter(v.Text, v.Start, v.End);
        if (actual.Equals(v.Expected)) return null;
        return v.Id + ": text=" + Show(v.Text) + " [" + v.Start + "," + v.End + ")"
            + "\n    expected " + Show(v.Expected) + "\n    actual   " + Show(actual);
    }

    /// <summary>The mismatch for one capitalize vector, or null when it matches.</summary>
    private static string? CheckCapitalize(CapitalizeVector v)
    {
        var actual = SmartTyping.Capitalize(v.Text, v.Start, v.End, v.Typed);
        if (string.Equals(actual, v.Expected, StringComparison.Ordinal)) return null;
        return v.Id + ": text=" + Show(v.Text) + " [" + v.Start + "," + v.End + ") typed=" + Show(v.Typed)
            + "\n    expected " + Show(v.Expected) + "\n    actual   " + Show(actual);
    }

    // MARK: - The oracle, whole

    [Fact]
    public void CorpusCarriesTheCountsItDeclares()
    {
        Assert.Equal(512, V.EnterCount);
        Assert.Equal(838, V.CapitalizeCount);
        Assert.Equal(V.EnterCount, V.Enter.Length);
        Assert.Equal(V.CapitalizeCount, V.Capitalize.Length);
        Assert.Equal(1350, V.Enter.Length + V.Capitalize.Length);
        // ids are unique across both arrays
        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (var v in V.Enter) Assert.True(ids.Add(v.Id), "duplicate id " + v.Id);
        foreach (var v in V.Capitalize) Assert.True(ids.Add(v.Id), "duplicate id " + v.Id);
        // every typed is exactly one scalar
        foreach (var v in V.Capitalize)
        {
            var runes = v.Typed.EnumerateRunes().GetEnumerator();
            Assert.True(runes.MoveNext() && !runes.MoveNext(), v.Id + ": typed is not one scalar: " + Show(v.Typed));
        }
    }

    [Fact]
    public void EveryEnterVectorMatches()
    {
        var failures = new List<string>();
        foreach (var v in V.Enter)
        {
            var failure = CheckEnter(v);
            if (failure is not null) failures.Add(failure);
        }
        Assert.True(failures.Count == 0,
            failures.Count + " of " + V.Enter.Length + " enter vectors failed:\n" + string.Join("\n", failures));
    }

    [Fact]
    public void EveryCapitalizeVectorMatches()
    {
        var failures = new List<string>();
        foreach (var v in V.Capitalize)
        {
            var failure = CheckCapitalize(v);
            if (failure is not null) failures.Add(failure);
        }
        Assert.True(failures.Count == 0,
            failures.Count + " of " + V.Capitalize.Length + " capitalize vectors failed:\n" + string.Join("\n", failures));
    }

    // MARK: - The oracle, one case per vector

    [Theory]
    [MemberData(nameof(EnterIds))]
    public void EnterVectorMatches(string id)
    {
        var failure = CheckEnter(EnterById.Value[id]);
        Assert.True(failure is null, failure);
    }

    [Theory]
    [MemberData(nameof(CapitalizeIds))]
    public void CapitalizeVectorMatches(string id)
    {
        var failure = CheckCapitalize(CapitalizeById.Value[id]);
        Assert.True(failure is null, failure);
    }

    // MARK: - Readable cases (each is also somewhere in the oracle)

    [Fact]
    public void BulletItemContinuesWithTheSameBullet()
    {
        // §1.4: insert "\n- " at the caret; the caret lands after the new marker.
        var edit = SmartTyping.Enter("- item", 6, 6);
        Assert.Equal(new SmartTyping.EnterEdit(6, 0, "\n- ", 9), edit);
    }

    [Fact]
    public void OrderedItemContinuesWithTheNextNumber()
    {
        Assert.Equal(new SmartTyping.EnterEdit(6, 0, "\n2. ", 10), SmartTyping.Enter("1. one", 6, 6));
        Assert.Equal(new SmartTyping.EnterEdit(7, 0, "\n2. ", 11), SmartTyping.Enter("01. one", 7, 7));
    }

    [Fact]
    public void EmptyItemEndsTheList()
    {
        // §1.3b: the empty "- " line is replaced by nothing; the caret stays on that (now empty) line.
        var edit = SmartTyping.Enter("- item\n- ", 9, 9);
        Assert.Equal(new SmartTyping.EnterEdit(7, 2, "", 7), edit);
    }

    [Fact]
    public void EmptyNestedItemOutdentsToItsParent()
    {
        // §1.3a: "- a" / "  - " with the caret at the end of the child → the child line becomes "- ".
        var edit = SmartTyping.Enter("- a\n  - ", 8, 8);
        Assert.Equal(new SmartTyping.EnterEdit(4, 4, "- ", 6), edit);
    }

    [Fact]
    public void TableRowInsertsAnEmptyRowBelow()
    {
        // §1.1: a new row padded to the header's column count, caret after its "| ".
        const string table = "| a | b |\n|---|---|\n| 1 | 2 |";
        var edit = SmartTyping.Enter(table, table.Length, table.Length);
        Assert.Equal(new SmartTyping.EnterEdit(table.Length, 0, "\n|  |  |", table.Length + 3), edit);
    }

    [Fact]
    public void TableHeaderInsertsTheRowAfterTheDelimiter()
    {
        const string table = "| a | b |\n|---|---|";
        var edit = SmartTyping.Enter(table, 9, 9);
        Assert.Equal(new SmartTyping.EnterEdit(table.Length, 0, "\n|  |  |", table.Length + 3), edit);
    }

    [Fact]
    public void CaretInsideThePrefixIsAPlainNewline()
    {
        Assert.Null(SmartTyping.Enter("- item", 1, 1));   // §1.2
        Assert.Null(SmartTyping.Enter("# Title", 7, 7));  // §1.5
        Assert.Null(SmartTyping.Enter("-", 1, 1));        // a bare marker is content (§0.11)
    }

    [Fact]
    public void CapitalAtTheLineStart()
    {
        Assert.Equal("H", SmartTyping.Capitalize("", 0, 0, "h"));
        Assert.Equal("J", SmartTyping.Capitalize("Notes\n", 6, 6, "j"));
        Assert.Equal("I", SmartTyping.Capitalize("- ", 2, 2, "i"));
        Assert.Equal("T", SmartTyping.Capitalize("# ", 2, 2, "t"));
    }

    [Fact]
    public void CapitalAfterASentence()
    {
        Assert.Equal("W", SmartTyping.Capitalize("Hello. ", 7, 7, "w"));
        Assert.Equal("Y", SmartTyping.Capitalize("Really?! ", 9, 9, "y"));
        Assert.Null(SmartTyping.Capitalize("wait... ", 8, 8, "w"));   // ellipsis
        Assert.Null(SmartTyping.Capitalize("e.g. ", 5, 5, "n"));      // abbreviation
        Assert.Null(SmartTyping.Capitalize("don'", 4, 4, "t"));       // no whitespace before the letter
    }

    [Fact]
    public void NoCapitalInsideAFenceOrATableCell()
    {
        Assert.Null(SmartTyping.Capitalize("```\ncode. ", 10, 10, "t"));
        Assert.Null(SmartTyping.Capitalize("| name |\n|---|\n| ", 17, 17, "n"));
        Assert.Null(SmartTyping.Capitalize("$x + ", 5, 5, "t"));         // inline math
        Assert.Null(SmartTyping.Enter("```\n- item", 10, 10));           // §1.0: a fence body is not a list
    }

    [Fact]
    public void TypedMustBeOneLowercaseLetterWithAnUppercase()
    {
        Assert.Null(SmartTyping.Capitalize("", 0, 0, "H"));           // already uppercase
        Assert.Null(SmartTyping.Capitalize("", 0, 0, "1"));           // a digit
        Assert.Null(SmartTyping.Capitalize("", 0, 0, "ß"));      // ß: no one-scalar uppercase
        Assert.Null(SmartTyping.Capitalize("", 0, 0, "µ"));      // MICRO SIGN, excluded by §0.7
        Assert.Null(SmartTyping.Capitalize("", 0, 0, "ა"));      // Georgian, excluded by §0.7
        Assert.Null(SmartTyping.Capitalize("", 0, 0, "ab"));          // two scalars
        Assert.Null(SmartTyping.Capitalize("", 0, 0, ""));            // none
        Assert.Equal("I", SmartTyping.Capitalize("", 0, 0, "ı"));           // dotless i: the Unicode simple mapping
        Assert.Equal("\U00010400", SmartTyping.Capitalize("", 0, 0, "\U00010428")); // a non-BMP letter (Deseret)
    }

    // MARK: - Lone surrogates: the native test the JSON cannot carry (§4.2)

    [Fact]
    public void ALoneSurrogateIsNeverALetter()
    {
        // §2.1a: a lone half is a scalar of category Cs — not lowercase, no uppercase.
        Assert.Null(SmartTyping.Capitalize("", 0, 0, "\uD800"));
        Assert.Null(SmartTyping.Capitalize("", 0, 0, "\uDC00"));
        // and as text it is content, never whitespace or a letter
        Assert.Equal("T", SmartTyping.Capitalize("\uD800. ", 3, 3, "t"));
    }

    [Fact]
    public void ACaretBetweenTheHalvesOfAPairIsRefused()
    {
        // §0.9: "- a😀" with the caret between the high and the low half → null for both.
        const string text = "- a😀";
        Assert.Null(SmartTyping.Enter(text, 4, 4));
        Assert.Null(SmartTyping.Capitalize(text, 4, 4, "t"));
        Assert.Null(SmartTyping.Enter(text, 0, 4));
        Assert.Null(SmartTyping.Capitalize(text, 4, 5, "t"));
        // after the pair both work
        Assert.Equal(new SmartTyping.EnterEdit(5, 0, "\n- ", 8), SmartTyping.Enter(text, 5, 5));
    }

    [Fact]
    public void AnOffsetOutsideTheTextOrBetweenCrAndLfIsRefused()
    {
        Assert.Null(SmartTyping.Enter("- a", 4, 4));
        Assert.Null(SmartTyping.Enter("- a", -1, 0));
        Assert.Null(SmartTyping.Capitalize("- a", 0, 4, "t"));
        Assert.Null(SmartTyping.Enter("- a\r\n- b", 4, 4));
        Assert.Null(SmartTyping.Capitalize("- a\r\n- b", 4, 4, "t"));
    }

    // MARK: - Cost (informational)

    /// <summary>
    /// A one-megabyte document with the caret at its end: both functions must stay in the
    /// keystroke budget (§0.14: one forward pass to the caret's line, every other walk bounded
    /// by the caret's run). The timings are logged, not asserted — CI machines are slower and a
    /// wall-clock bound in a unit test is the flake this family has already paid for — but the
    /// results themselves are checked, so the run cannot pass by doing nothing.
    /// </summary>
    [Fact]
    public void OneMegabyteDocumentStaysInTheKeystrokeBudget()
    {
        var builder = new StringBuilder(1_100_000);
        const string block =
            "# Section\n\nSome prose with a sentence. Another one follows here, and a `code span` too.\n\n"
            + "- first item\n- second item\n  - nested item\n- [ ] task\n\n"
            + "| a | b |\n|---|---|\n| 1 | 2 |\n\n"
            + "```\ncode. not capitalized\n```\n\n"
            + "> quoted line. Next sentence\n> - quoted item\n\n";
        while (builder.Length < 1_048_576) builder.Append(block);
        builder.Append("Hello. ");
        var capitalizeText = builder.ToString();
        var enterText = capitalizeText + "\n- item";
        Assert.True(enterText.Length > 1_048_576, "the document is at least one megabyte");

        // one warm-up so the JIT and the first-touch allocations are not what is measured
        _ = SmartTyping.Enter(enterText, enterText.Length, enterText.Length);
        _ = SmartTyping.Capitalize(capitalizeText, capitalizeText.Length, capitalizeText.Length, "t");

        var sw = Stopwatch.StartNew();
        var edit = SmartTyping.Enter(enterText, enterText.Length, enterText.Length);
        var enterMs = sw.Elapsed.TotalMilliseconds;
        sw.Restart();
        var capital = SmartTyping.Capitalize(capitalizeText, capitalizeText.Length, capitalizeText.Length, "t");
        var capitalizeMs = sw.Elapsed.TotalMilliseconds;

        _output.WriteLine("SmartTyping on a " + enterText.Length.ToString(CultureInfo.InvariantCulture)
            + "-unit document, caret at the end: enter " + enterMs.ToString("F2", CultureInfo.InvariantCulture)
            + " ms, capitalize " + capitalizeMs.ToString("F2", CultureInfo.InvariantCulture)
            + " ms (informational; the budget is 100 ms on the development machine)");

        Assert.Equal(new SmartTyping.EnterEdit(enterText.Length, 0, "\n- ", enterText.Length + 3), edit);
        Assert.Equal("T", capital);
    }
}
